### ISSUE TITLE
test_scale_osds_fill_75%_reboot_workers boto credential error -- may be caused by pvc creation timeouts.

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3457] opened 2020-12-01 22:41 UTC
See attached log
[test_scale_75.log](https://github.com/red-hat-storage/ocs-ci/files/5625896/test_scale_75.log)

**Comment by wusui** [comment] 2020-12-01 22:42
3455, 3456, 3457 are all different problems but these may be caused by similar timeout issues.

**Comment by ramkiperiy** [comment] 2021-05-03 15:46
Not observed this issue for quite sometime, will check in another couple of runs and decide to fix or close this issue.

**Comment by ramkiperiy** [comment] 2021-08-25 07:27
Closing this issues, since the problem is not observed in last 3 month test runs.

**Closed by ramkiperiy** 2021-08-25 07:27 UTC
Labels: bug, scale, Squad/Orange
