### ISSUE TITLE
ceph rbd metrics collection missing on s390 platform

### ISSUE THREAD

**Issue by venkat-pinisetti** [red-hat-storage/ocs-ci#2591] opened 2020-07-30 05:48 UTC
**Summary:**
Below testcase failed while running on s390x platform on ocs4.4 version.

**Environment:**
Config : Baremetal
Arch : s390 (z)
Testcase : test_ceph_rbd_metrics_available

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py::test_ceph_rbd_metrics_available 
```
-------------------------------- live log setup --------------------------------
09:33:26 - MainThread - tests.conftest - INFO - All logs located at /tmp/ocs-ci-logs-1595511203
09:33:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: /root/ocs-ci/bin/oc version --client
09:33:26 - MainThread - ocs_ci.utility.utils - INFO - OpenShift Client version: Client Version: 4.4.10

09:33:26 - MainThread - ocs_ci.ocs.version - INFO - collecting ocs version
09:33:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get clusterversion version -o yaml
09:33:27 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get namespace  -o yaml
09:33:28 - MainThread - ocs_ci.ocs.version - INFO - found storage namespaces ['openshift-cluster-storage-operator', 'openshift-kube-storage-version-migrator', 'openshift-kube-storage-version-migrator-operator', 'openshift-storage']
09:33:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-cluster-storage-operator --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get pod  -n openshift-cluster-storage-operator -o yaml
09:33:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-kube-storage-version-migrator --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get pod  -n openshift-kube-storage-version-migrator -o yaml
09:33:29 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-kube-storage-version-migrator-operator --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get pod  -n openshift-kube-storage-version-migrator-operator -o yaml
09:33:30 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get pod  -n openshift-storage -o yaml
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - ClusterVersion .spec.channel: stable-4.4
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - ClusterVersion .status.desired.version: 4.4.10
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - ClusterVersion .status.desired.image: quay.io/openshift-release-dev/ocp-release@sha256:847bc8745485e94e98ef84cc6922c8071ff9ac978ae1c9925ce0ffde9d3f140e
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - storage namespace openshift-cluster-storage-operator
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:eb41a3827620c31c4606f2e646794df46ba8f0f55aa52850de88504ff1be7549 {'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:eb41a3827620c31c4606f2e646794df46ba8f0f55aa52850de88504ff1be7549'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8b3d0be100446352cd5d5a2b1b7f059be177611d300fedf40620201b42c26877 {'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:8b3d0be100446352cd5d5a2b1b7f059be177611d300fedf40620201b42c26877'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:20b6e5b5524ab2702ae55b932b64b3741d29662683f860b7fc7b955224bad6af {'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:20b6e5b5524ab2702ae55b932b64b3741d29662683f860b7fc7b955224bad6af'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - storage namespace openshift-kube-storage-version-migrator
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2d203454d4e22a1e7f60c9318e489895f2a33474b64af430e5f92ca710ac7215 {'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:2d203454d4e22a1e7f60c9318e489895f2a33474b64af430e5f92ca710ac7215'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - storage namespace openshift-kube-storage-version-migrator-operator
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:728b2a56b8d7899f7e5c5897fbc95c5c4c792aea745eadf2a83e4d6d27fda877 {'quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:728b2a56b8d7899f7e5c5897fbc95c5c4c792aea745eadf2a83e4d6d27fda877'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - storage namespace openshift-storage
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-cephcsi-rhel8:4.4-4 {'quay.io/multi-arch/ocs4-cephcsi-rhel8@sha256:30e9620af9ee393dd3ca8975c25a008414f320166ac8ddd7efc5a5ad19c75ee9'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image registry.redhat.io/openshift4/ose-csi-node-driver-registrar:v4.4 {'registry.redhat.io/openshift4/ose-csi-node-driver-registrar@sha256:31112a926725e4031a656d65e9ddd64be6e62b24dfaaa13b8e226214498d41aa'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image registry.redhat.io/openshift4/ose-csi-external-attacher:v4.4 {'registry.redhat.io/openshift4/ose-csi-external-attacher@sha256:733f554b9a3c515f0bccf0eb3be409c4443078f4d4fc06b227528d52b47761c0'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7:v4.4 {'registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel7@sha256:02478968eef0e2926f092b72001c711c1989d2355ee6f5429e198eb1fa817c39'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image registry.redhat.io/openshift4/ose-csi-external-resizer-rhel7:v4.4 {'registry.redhat.io/openshift4/ose-csi-external-resizer-rhel7@sha256:539f48c42d8ce0d90ed409311a1c32c73692e97f0fc185d7f4cda2f11d120d0e'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/noobaa/pause:latest {'quay.io/noobaa/pause@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-mcg-core-rhel8:4.4-4 {'quay.io/multi-arch/ocs4-mcg-core-rhel8@sha256:0d428cbe478380ee46d2e5e068d822e5e3ec67d956189bc4e8b0846a4818abee'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image registry.redhat.io/rhscl/mongodb-36-rhel7:latest {'registry.redhat.io/rhscl/mongodb-36-rhel7@sha256:3292de73cb0cd935cb20118bd86e9ddbe8ff8c0a8d171cf712b46a0dbd54e169'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-mcg-rhel8-operator:4.4-4 {'quay.io/multi-arch/ocs4-mcg-rhel8-operator@sha256:a17c6042e7b26f8616ad111daed64cc2bfe518e599b85600b4a7812a5c7ee705'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-ocs-rhel8-operator:4.4-4 {'quay.io/multi-arch/ocs4-ocs-rhel8-operator@sha256:0938c8b46eb435679a946d32817af2e61fc4633f668063f4953131c65308071c'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/rhceph-rhceph-4-rhel8:4 {'quay.io/multi-arch/rhceph-rhceph-4-rhel8@sha256:473d7f62be1be66e26e3c7060679cbeb363a52498d4b5908764fe2c504a921fa'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-rook-ceph-rhel8-operator:4.4-4 {'quay.io/multi-arch/ocs4-rook-ceph-rhel8-operator@sha256:690426c2bedac5b692c459b08171b5d41bb771a32daedb4bda57d4fb46e93744'}
09:33:34 - MainThread - ocs_ci.ocs.version - INFO - image quay.io/multi-arch/ocs4-rook-ceph-rhel8-operator:4.4 {'quay.io/multi-arch/ocs4-rook-ceph-rhel8-operator@sha256:690426c2bedac5b692c459b08171b5d41bb771a32daedb4bda57d4fb46e93744'}
09:33:34 - MainThread - tests.conftest - INFO - human readable ocs version info written into /root/ocp4-workdir-ocs/ocs_version.2020-07-23T09:33:34.609647
09:33:34 - MainThread - ocs_ci.utility.utils - INFO - testrun_name: OCS4-4-Downstream-OCP4-5-BAREMETAL-UPI-1AZ-RHCOS-3M-3W-
09:33:34 - MainThread - ocs_ci.utility.utils - INFO - The rook directory /root/ocs-ci/data/rook already exists, ocs-ci will skip the clone of rook repository.
09:33:34 - MainThread - ocs_ci.utility.utils - INFO - Fetching latest changes from rook repository.
09:33:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git fetch --all
09:33:35 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: From https://github.com/rook/rook
   dcadf10f..0795204b  master     -> origin/master

09:33:35 - MainThread - ocs_ci.utility.utils - INFO - Checkout rook repository to specific branch: master
09:33:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git checkout master
09:33:35 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Already on 'master'

09:33:35 - MainThread - ocs_ci.utility.utils - INFO - Reset branch: master with latest changes
09:33:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: git reset --hard origin/master
09:33:35 - MainThread - tests.conftest - INFO - Checking for Ceph Health OK 
09:33:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc wait --for condition=ready pod -l app=rook-ceph-tools -n openshift-storage --timeout=120s
09:33:36 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage get pod -l 'app=rook-ceph-tools' -o jsonpath='{.items[0].metadata.name}'
09:33:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage exec rook-ceph-tools-6f97d4dfb9-fp78q -- ceph health
09:33:39 - MainThread - ocs_ci.utility.utils - INFO - Ceph cluster health is HEALTH_OK.
09:33:39 - MainThread - tests.conftest - INFO - Ceph health check passed at setup
-------------------------------- live log call ---------------------------------
09:33:39 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc login -u kubeadmin -p Wew9x-onXJZ-ZQ9tx-qCKUm
09:33:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig whoami --show-token
09:33:43 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /root/ocp4-workdir-ocs/auth/kubeconfig get Route prometheus-k8s -n openshift-monitoring -o yaml
09:33:43 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Generated CA certification file: /tmp/tmplc6suwyy
09:33:43 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_write_ops'
09:33:44 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_write_ops
09:33:44 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_read_ops'
09:33:45 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_read_ops
09:33:45 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_write_bytes'
09:33:45 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_write_bytes
09:33:45 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_read_bytes'
09:33:46 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_read_bytes
09:33:46 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_write_latency_sum'
09:33:46 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_write_latency_sum
09:33:46 - MainThread - /root/ocs-ci/ocs_ci/utility/prometheus.py - INFO - Performing prometheus instant query 'ceph_rbd_write_latency_count'
09:33:47 - MainThread - test_monitoring_defaults - ERROR - failed to get results for ceph_rbd_write_latency_count
FAILED    
```
```
=================================== FAILURES ===================================
____________________ test_ceph_rbd_metrics_available ________________________

    @tier1
    @pytest.mark.bugzilla("1779336")
    @pytest.mark.polarion_id("OCS-1267")
    def test_ceph_rbd_metrics_available():
        """
        Ceph RBD metrics should be provided via OCP Prometheus as well.
        See also: https://ceph.com/rbd/new-in-nautilus-rbd-performance-monitoring/
        """
        # this is not a full list, but it is enough to check whether we have
        # rbd metrics available via OCS monitoring
        list_of_metrics = [
            "ceph_rbd_write_ops",
            "ceph_rbd_read_ops",
            "ceph_rbd_write_bytes",
            "ceph_rbd_read_bytes",
            "ceph_rbd_write_latency_sum",
            "ceph_rbd_write_latency_count"]
    
        prometheus = PrometheusAPI()
    
        list_of_metrics_without_results = []
        for metric in list_of_metrics:
            result = prometheus.query(metric)
            # check that we actually received some values
            if len(result) == 0:
                logger.error(f"failed to get results for {metric}")
                list_of_metrics_without_results.append(metric)
        msg = (
            "OCS Monitoring should provide some value(s) for tested rbd metrics, "
            "so that the list of metrics without results is empty.")
>       assert list_of_metrics_without_results == [], msg
E       AssertionError: OCS Monitoring should provide some value(s) for tested rbd metrics, so that the list of metrics without results is empty.
E       assert ['ceph_rbd_write_ops',\n 'ceph_rbd_read_ops',\n 'ceph_rbd_write_bytes',\n 'ceph_rbd_read_bytes',\n 'ceph_rbd_write_latency_sum',\n 'ceph_rbd_write_latency_count'] == []
E         Left contains 6 more items, first extra item: 'ceph_rbd_write_ops'
E         Full diff:
E           [
E         +  ,
E         -  'ceph_rbd_write_ops',
E         -  'ceph_rbd_read_ops',
E         -  'ceph_rbd_write_bytes',
E         -  'ceph_rbd_read_bytes',
E         -  'ceph_rbd_write_latency_sum',
E         -  'ceph_rbd_write_latency_count',
E           ]

tests/manage/monitoring/prometheusmetrics/test_monitoring_defaults.py:122: AssertionError
```

**Comment by ebenahar** [comment] 2020-08-26 10:28
Hi @venkat-pinisetti could you please report a Bugzilla for this issue?

**Comment by PrasadDesala** [comment] 2020-08-26 10:39
> Hi @venkat-pinisetti could you please report a Bugzilla for this issue?

FYI. From the above pasted output, I see the test is having a BZ decorator 
It seems to be the same issue https://bugzilla.redhat.com/show_bug.cgi?id=1779336

**Comment by venkat-pinisetti** [comment] 2020-08-26 10:43
I'm not able to access this https://bugzilla.redhat.com/show_bug.cgi?id=1779336. Can you give me the access.

**Comment by gitsridhar** [comment] 2020-08-27 13:52
@venkat-pinisetti you will need VPN access using RedHat Id. I am able to access this bugzilla bug.

**Comment by gitsridhar** [comment] 2020-08-27 13:57
Problem description (from 1779336) : Description of problem
======================

OCP Prometheus instance in OCS cluster doesn't provide RBD Performance metrics
(ceph_rbd_*).

Version-Release number of selected component
============================================

cluster channel: stable-4.2
cluster version: 4.2.0-0.nightly-2019-12-02-165545
cluster image: registry.svc.ci.openshift.org/ocp/release@sha256:159ba31ba77bc5ae78d09caca06eada94483b27f4f8e8afafdfa036b42bd3d80

storage namespace openshift-cluster-storage-operator
image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1f2819a25c4f1945d3a2a63e64b89a4f1f095cbb34e39829785e966151340fdc
 * quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:1f2819a25c4f1945d3a2a63e64b89a4f1f095cbb34e39829785e966151340fdc

storage namespace openshift-storage
image quay.io/rhceph-dev/cephcsi:4.2-225.72ac53b6.release_4.2
 * quay.io/rhceph-dev/cephcsi@sha256:69950f3c8bdf6889e85deafdbc8d07e63910337435d2f5d6a1ba674d08f85c51
image quay.io/openshift/origin-csi-node-driver-registrar:4.2
 * quay.io/openshift/origin-csi-node-driver-registrar@sha256:6671a4a02a9bf5abfa58087b6d2fea430278d7bc5017aab6b88a84203c0dad06
image quay.io/openshift/origin-csi-external-attacher:4.2
 * quay.io/openshift/origin-csi-external-attacher@sha256:dafeaa49292fce721c1ed763efd1f45b02a9c4f78d7087a854067c5e2718d93c
image quay.io/openshift/origin-csi-external-provisioner:4.2
 * quay.io/openshift/origin-csi-external-provisioner@sha256:dbe8b5e1bebfed1e8f68be1d968ff0356270a0311c21f3920e0f3bec3b4d97ea
image quay.io/openshift/origin-csi-external-snapshotter:4.2
 * quay.io/openshift/origin-csi-external-snapshotter@sha256:910f54893ac1ae42b80735b0def153ee62aa7a73d5090d2955afc007b663ec79
image quay.io/rhceph-dev/mcg-core:5.2.11-20.59b35a4f0.5.2
 * quay.io/rhceph-dev/mcg-core@sha256:3f9da7525a751837750cfe8fd49d8707090c7a1c4e257c23b882184e5f97f76e
image registry.access.redhat.com/rhscl/mongodb-36-rhel7:latest
 * registry.access.redhat.com/rhscl/mongodb-36-rhel7@sha256:c845fa631fafab54addb20e33af2a8bc2a693af07ffd9a9fa1bc2715d39b40ca
image quay.io/rhceph-dev/mcg-operator:2.0.9-35.db6a79b.2.0
 * quay.io/rhceph-dev/mcg-operator@sha256:e065c52e0132450477223f4262a495db84de0963ed639457c961e52c36618f35
image quay.io/rhceph-dev/ocs-operator:4.2-259.e29a26e.release_4.2
 * quay.io/rhceph-dev/ocs-operator@sha256:339ad733e127e7eb182e46cfd74200615c42bd4f1d44331e2f13479b8ccfad8d
image quay.io/rhceph-dev/rook-ceph:4.2-257.9a1d8592.ocs_4.2
 * quay.io/rhceph-dev/rook-ceph@sha256:1ae7998e77ccea9a07a39da0d196326d9e485d05bd24df48c088a740dd219410
image quay.io/rhceph-dev/rhceph:4-119.20191128.ci.0
 * quay.io/rhceph-dev/rhceph@sha256:2bbb7704bae17b8a20c6ff1c240d2b1e83cd185fff2aa80ccc85968365cbb4e0

Note: rhceph:4-119.2019112 image comes with Nautilus, as can be seen in output
of ceph version command:

```
# ceph --version
ceph version 14.2.4-55.el8cp (4f4ac92930e1b5abf963781f77361a7dd4cffafa) nautilus (stable)
```

How reproducible
================

100%

Steps to Reproduce
==================

1. Install OCP/OCS cluster (I did this via red-hat-storage/ocs-ci, using
   downstream OCS images, ocs-ci commit 89a1698)
2. Login as kubeadmin to OCP Console
3. Go to Monitoring -> Metrics page
4. Type eg. ceph_rbd_write_ops into the query and run it

Actual results
==============

There are no results, the metric is not defined.

Expected results
================

Values are provided.

Additional info
===============

RBD Performance metrics (ceph_rbd_*) are available since Nautilus:
https://ceph.com/rbd/new-in-nautilus-rbd-performance-monitoring/

https://jira.coreos.com/browse/KNIP-634?focusedCommentId=117344&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-117344

**Comment by lsmcfadden** [comment] 2020-10-14 15:12
@venkat-pinisetti so is this being worked thru bugzilla and we close this issue or what is the next step?

**Comment by umangachapagain** [comment] 2020-11-05 04:30
Ceph RBD metrics are not available by default. So these tests are bound to fail.
We should skip these tests for now.

**Comment by mbukatov** [comment] 2020-11-05 09:21
Fixed by https://github.com/red-hat-storage/ocs-ci/pull/3176 based on https://bugzilla.redhat.com/show_bug.cgi?id=1779336#c34.

**Closed by mbukatov** 2020-11-05 09:21 UTC
