### ISSUE TITLE
run-ci - making optional collecting  must-gather logs in the Teardown phase of test run

### ISSUE THREAD

**Issue by ypersky1980** [red-hat-storage/ocs-ci#3011] opened 2020-09-29 22:17 UTC
The problem is that each time we run the test and there is a failure , we have to wait at least 45 mins to have the test finish the Teardown phase, since it collects must-gather logs each time. 
It would be good to have an option used only for development process to skip the long log creation and shorten the run time of tests. 
I mean - a flag in command line. If it's not specified - let the teardown collect must-gather logs by default. 
If this flag is specified ( --nomustgather for example) - let the teardown finishe quickly by only removing instances from the cluster, but not collecting logs.

**Comment by petr-balogh** [comment] 2020-09-30 09:43
Hey @ypersky1980 , there is COLLECT_LOGS parameter which can be unchecked to not collect the logs in the deploy job on our QE jenkins or  CLI parameter: `--collect-logs` which cannot be used.

There was recently introduced new feature when we collect logs on also successful execution/deployment. And it's already discussed in this issue: https://github.com/red-hat-storage/ocs-ci/issues/3001

So I think that this issue is just duplicate of issue opened by Vasu ^. 

So I will close this one and please add your comment to the issue #3001 if that's what you want. I added comment there as well with the approach.

@jimdevops19  FYI.

**Closed by petr-balogh** 2020-09-30 09:43 UTC
