### ISSUE TITLE
Resource requests for memory and CPU are set to null

### ISSUE THREAD

**Issue by MeridianExplorer** [red-hat-storage/ocs-ci#1017] opened 2019-11-17 16:25 UTC
As discussed in the [Google Chat thread](https://chat.google.com/u/0/room/AAAAREGEba8/ET7p21O3Qd8), the deployment process of OCS-CI seems to either never set the resource requests, or set them all to null.
This results in, for example, NooBaa's resource requests and limits all being set to '0'.

@petr-balogh - What do you think?

**Comment by petr-balogh** [comment] 2019-11-18 22:36
As I explained you today in your thread it's cause of for development purpose we by default enable to deploy on lower instance types.

If you don't want to set those limits/requests to null you just need to use production config https://github.com/red-hat-storage/ocs-ci/blob/master/conf/ocsci/production-aws-ipi.yaml#L3 or just create another config which will have this option 
```yaml
DEPLOYMENT:
  allow_lower_instance_requirements: false
```

So closing this issue as this is not a bug but by design in ocs-ci.
If I missed something, please let me know @MeridianExplorer

**Closed by petr-balogh** 2019-11-18 22:36 UTC
Labels: bug
