### ISSUE TITLE
Timeout is seen during deployment when using "--ocsci-conf conf/ocsci/host_network_enabled.yaml"

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#921] opened 2019-10-21 18:11 UTC
-  ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed Out: (600,) is seen
- No osd pods are created
- ocs full log: https://paste.fedoraproject.org/paste/YiCzI-g~A8~-PcKgXYpTUA

``` $ oc get pods -n openshift-storage
NAME                                            READY   STATUS    RESTARTS   AGE
csi-cephfsplugin-ccz8p                          3/3     Running   0          26m
csi-cephfsplugin-ng8wf                          3/3     Running   0          26m
csi-cephfsplugin-provisioner-765c7b85b7-8gmzg   4/4     Running   0          26m
csi-cephfsplugin-provisioner-765c7b85b7-rm5mc   4/4     Running   0          26m
csi-cephfsplugin-wc8gh                          3/3     Running   0          26m
csi-rbdplugin-5jth7                             3/3     Running   0          26m
csi-rbdplugin-kwjj7                             3/3     Running   0          26m
csi-rbdplugin-provisioner-779d64bdc8-kdxgr      5/5     Running   0          26m
csi-rbdplugin-provisioner-779d64bdc8-wl76k      5/5     Running   0          26m
csi-rbdplugin-vs5hx                             3/3     Running   0          26m
local-storage-operator-6cf56d5cf-m99qt          1/1     Running   0          27m
noobaa-core-0                                   0/2     Pending   0          26m
noobaa-operator-656495d88f-sqgdb                1/1     Running   0          27m
ocs-operator-7f948c6b5-t442n                    0/1     Running   0          27m
rook-ceph-mgr-a-f54484c68-nwv9m                 1/1     Running   0          23m
rook-ceph-mon-a-7df7994667-vbj99                1/1     Running   0          25m
rook-ceph-mon-b-679f894bdf-zccck                1/1     Running   0          24m
rook-ceph-mon-c-6d8548d6b6-2nzfg                1/1     Running   0          24m
rook-ceph-operator-77778fdf4-dnjlh              1/1     Running   0          27m  ```

**Comment by petr-balogh** [comment] 2019-10-22 13:26
@tiffanyn108 did you look at the logs? Did you  collect must-gather logs? Have you opened bug? I didn't hit such issue when I verified and executed with host network so I would suggest you open the bug with all the details and maybe provide the access to such cluster when you see such kind of issue. I can try to reproduce in the jenkins but today we have problems to execute cause of issues with PSI openstack.

**Comment by keesturam** [comment] 2019-10-22 14:43
@petr-balogh I saw the same issue that Tiffany reported. 
@tiffanyn108 please go ahead and file a bug as Petr suggested. if you don't have a setup to file the bug, I can share one.

**Comment by tiffanyn108** [comment] 2019-10-22 15:53
@petr-balogh Bug has filed for this issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1764275
@keesturam I have a failing cluster which dev can take a look if they need to.  Thanks!

**Comment by vasukulkarni** [comment] 2019-10-23 20:41
Closing because there is a BZ

**Closed by vasukulkarni** 2019-10-23 20:41 UTC
Labels: High Priority
