### ISSUE TITLE
skipif version not working

### ISSUE THREAD

**Issue by Avilir** [red-hat-storage/ocs-ci#5260] opened 2021-12-21 07:03 UTC
all tests with the marker `skipif_ocs_version` < 4.6 not running on OCS 4.10

from acceptance test  : 
```
18:42:39 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:40 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_multiple_clone_performance[RBD]> will be skipped due to OCP ('<4.6',)
18:42:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:40 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_multiple_clone_performance[CephFS]> will be skipped due to OCP ('<4.6',)
18:42:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:40 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_multiple_snapshot_performance[RBD]> will be skipped due to OCP ('<4.6',)
18:42:40 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:41 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_multiple_snapshot_performance[CephFS]> will be skipped due to OCP ('<4.6',)
18:42:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:41 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[RBD-1]> will be skipped due to OCP ('<4.6',)
18:42:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:41 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[RBD-10]> will be skipped due to OCP ('<4.6',)
18:42:41 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:42 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[RBD-100]> will be skipped due to OCP ('<4.6',)
18:42:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:42 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[CephFS-1]> will be skipped due to OCP ('<4.6',)
18:42:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:42 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[CephFS-10]> will be skipped due to OCP ('<4.6',)
18:42:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc get clusterversion -n openshift-storage -o yaml
18:42:43 - MainThread - tests.conftest - INFO - Test: <Function test_pvc_snapshot_performance[CephFS-100]> will be skipped due to OCP ('<4.6',)
```

**Comment by ypersky1980** [comment] 2022-01-02 11:54
Looks like the issue is not resolved - when running https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/2728/consoleFull some of the tests were skipped with the reason : 

2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_bucket_creation[3-RGW-OC]> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_duplicate_bucket_creation[3-RGW-OC]> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_bucket_delete[3-RGW-OC]> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_bucket_delete_with_objects[RGW-OC]> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_nonexist_bucket_delete[RGW-OC]> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_rgw_host_node_failure> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_multipart_upload_operations> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_object_bucket_size> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_check_object_integrity> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5
2021-12-30 15:05:41  13:05:41 - MainThread - conftest - INFO - Test <Function test_empty_file_integrity> is removed from the collected items due to aws not being an on-prem platform or OCS version (4.10) being lower than 4.5

**Comment by ypersky1980** [comment] 2022-01-02 12:18
The tests run on the stable branch - is it the reason why the fix still was not applied ?

**Comment by petr-balogh** [comment] 2022-01-03 08:55
@ypersky1980 the PR fix was not promoted yet to stable branch. As I see last successful pipeline was triggered 9 days ago but PR got merged 7 days ago. I will check what happened in last executions of https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-ocs-ci-stable-branch-pipeline/ and let's see if it will succeed next time so we will get fix in soon.

**Comment by petr-balogh** [comment] 2022-01-03 08:56
As fix is in master already I am closing this one.

**Closed by petr-balogh** 2022-01-03 08:56 UTC
Labels: bug, High Priority
