### ISSUE TITLE
test_add_capacity_ui is failing with  selenium.common.exceptions.TimeoutException: Message:

### ISSUE THREAD

**Issue by pintojoy** [red-hat-storage/ocs-ci#6908] opened 2023-01-12 13:16 UTC
Message: selenium.common.exceptions.TimeoutException: Message:
Type: None

Text:
self = <tests.manage.z_cluster.cluster_expansion.test_add_capacity.TestAddCapacity object at 0x7f2dbe6298b0>
reduce_and_resume_cluster_load = None

@tier1
def test_add_capacity_ui(self, reduce_and_resume_cluster_load):
    """
    Add capacity on non-lso cluster via UI on tier1 suite
    """

  add_capacity_test(ui_flag=True)

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py:125: 

tests/manage/z_cluster/cluster_expansion/test_add_capacity.py:52: in add_capacity_test
    result = ui_add_capacity(osd_size)
ocs_ci/ocs/ui/helpers_ui.py:165: in ui_add_capacity
    setup_ui = login_ui()
ocs_ci/utility/retry.py:42: in f_retry
    return f(args, *kwargs)
ocs_ci/utility/retry.py:42: in f_retry
    return f(args, *kwargs)
ocs_ci/ocs/ui/base_ui.py:981: in login_ui
    element = wait.until(

self = <selenium.webdriver.support.wait.WebDriverWait (session="5ff513f8131e575023b8f3289c9fdb35")>
method = <selenium.webdriver.support.expected_conditions.element_to_be_clickable object at 0x7f2da00b7610>
message = ''

def until(self, method, message=''):
    """Calls the method provided with the driver as an argument until the \
    return value is not False."""
    screen = None
    stacktrace = None

    end_time = time.time() + self._timeout
    while True:
        try:
            value = method(self._driver)
            if value:
                return value
        except self._ignored_exceptions as exc:
            screen = getattr(exc, 'screen', None)
            stacktrace = getattr(exc, 'stacktrace', None)
        time.sleep(self._poll)
        if time.time() > end_time:
            break

  raise TimeoutException(message, screen, stacktrace)
E       selenium.common.exceptions.TimeoutException: Message:

venv/lib64/python3.8/site-packages/selenium/webdriver/support/wait.py:80: TimeoutException

https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/362/7968/347902/348193/348194/log

**Comment by am-agrawa** [comment] 2023-02-22 10:53
@OdedViner Is this issue fixed with the PR you were working on?

**Comment by am-agrawa** [comment] 2023-02-22 14:16
Fixed here-
[https://github.com/red-hat-storage/ocs-ci/pull/6896](https://www.google.com/url?q=https://github.com/red-hat-storage/ocs-ci/pull/6896&sa=D&source=docs&ust=1677078478682236&usg=AOvVaw2hyh7TDaZoZdltbHrQ-pgM)
[https://github.com/red-hat-storage/ocs-ci/pull/6959](https://www.google.com/url?q=https://github.com/red-hat-storage/ocs-ci/pull/6959&sa=D&source=docs&ust=1677078478682338&usg=AOvVaw3tBHwa0dbjJHKwDzhD_OI7)

Feel free to re-open if the issue is seen again.

**Closed by am-agrawa** 2023-02-22 14:16 UTC
Labels: ui_automation
