### ISSUE TITLE
 Exception: aws_client was not initialized, please verify the needed credentials were set in auth.yaml AttributeError: 'CloudManager' object has no attribute 'aws_client'

### ISSUE THREAD

**Issue by petr-balogh** [red-hat-storage/ocs-ci#3411] opened 2020-11-25 11:54 UTC
In the engineering pipeline I saw this failure:
https://storage-jenkins-csb-ceph.cloud.paas.psi.redhat.com/job/ocs-ci/120/consoleFull

```
                "please verify the needed credentials "
>               "were set in auth.yaml".format(str(e).split("'")[3])
            )
E           Exception: aws_client was not initialized, please verify the needed credentials were set in auth.yaml

ocs_ci/ocs/resources/cloud_uls.py:40: Exception
____ ERROR at setup of TestBucketCreation.test_bucket_creation[3-CLI-None] _____


        try:
            ulsMap = {
>               "aws": cld_mgr.aws_client,
                "gcp": cld_mgr.gcp_client,
                "azure": cld_mgr.azure_client,
                "ibmcos": cld_mgr.ibmcos_client,
            }
E           AttributeError: 'CloudManager' object has no attribute 'aws_client'

ocs_ci/ocs/resources/cloud_uls.py:31: AttributeError

During handling of the above exception, another exception occurred:

request = <SubRequest 'cloud_uls_factory' for <Function test_bucket_creation[3-S3-None]>>
cld_mgr = <ocs_ci.ocs.resources.cloud_manager.CloudManager object at 0x7f0307ad1390>

    @pytest.fixture(scope="class")
    def cloud_uls_factory(request, cld_mgr):
        """
        Create an Underlying Storage factory.
        Calling this fixture creates a new underlying storage(s).
    
        Returns:
           func: Factory method - each call to this function creates
               an Underlying Storage factory
    
        """
>       return cloud_uls_factory_implementation(request, cld_mgr)

tests/conftest.py:1991: 
```

**Comment by ebenahar** [comment] 2020-11-25 12:17
I guess this will be fixed with https://github.com/red-hat-storage/ocs-ci/pull/3382

**Comment by MeridianExplorer** [comment] 2020-11-25 12:20
@ebenahar is correct 👍🏻
Thanks.
Closing this as a duplicate of #3361

**Closed by MeridianExplorer** 2020-11-25 12:20 UTC
Labels: High Priority
