### ISSUE TITLE
scale/test_pv_scale_and_respin_ceph_pods.py has intermittent Ceph failurs on Vms

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#2761] opened 2020-08-19 08:57 UTC
The following error sometimes occurs when running test_pv_scale_and respin_ceph_pods.py on Vms.  This problem does not seem to occur on AWS.

E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 MDSs report slow metadata IOs
ocs_ci/utility/utils.py:1360: CephHealthException

**Comment by wusui** [comment] 2020-08-19 08:57
Currently being investigated.  I am trying to reproduce.

**Comment by ramkiperiy** [comment] 2021-04-19 04:53
Not observing this problem in the recent times, and the issue is quite old. 
Closing this issue

**Closed by ramkiperiy** 2021-04-19 04:53 UTC
