### ISSUE TITLE
test_clone_pvc[ocs-storagecluster-cephfs-ReadWriteMany-ReadWriteOnce] fails during teardown on disconnected cluster

### ISSUE THREAD

**Issue by rachael-george** [red-hat-storage/ocs-ci#6980] opened 2023-01-24 11:28 UTC
The test `test_clone_pvc[ocs-storagecluster-cephfs-ReadWriteMany-ReadWriteOnce]` fails on teardown with the following error:

```
Message: failed on teardown with "ValueError: file descriptor cannot be a negative integer (-1)"
Type: None

Text:
def finalizer():
  close_browser(driver)

tests/conftest.py:4497: 

ocs_ci/ocs/ui/base_ui.py:1031: in close_browser
    garbage_collector_webdriver()
ocs_ci/ocs/ui/base_ui.py:849: in garbage_collector_webdriver
    obj.close()
venv/lib64/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:688: in close
    self.execute(Command.CLOSE)
venv/lib64/python3.8/site-packages/selenium/webdriver/remote/webdriver.py:319: in execute
    response = self.command_executor.execute(driver_command, params)
venv/lib64/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py:374: in execute
    return self._request(command_info[0], url, body=data)
venv/lib64/python3.8/site-packages/selenium/webdriver/remote/remote_connection.py:397: in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
venv/lib64/python3.8/site-packages/urllib3/request.py:75: in request
    return self.request_encode_url(
venv/lib64/python3.8/site-packages/urllib3/request.py:97: in request_encode_url
    return self.urlopen(method, url, *extra_kw)
venv/lib64/python3.8/site-packages/urllib3/poolmanager.py:336: in urlopen
    response = conn.urlopen(method, u.request_uri, *kw)
venv/lib64/python3.8/site-packages/urllib3/connectionpool.py:659: in urlopen
    conn = self._get_conn(timeout=pool_timeout)
venv/lib64/python3.8/site-packages/urllib3/connectionpool.py:270: in _get_conn
    if conn and is_connection_dropped(conn):
venv/lib64/python3.8/site-packages/urllib3/util/connection.py:24: in is_connection_dropped
    return wait_for_read(sock, timeout=0.0)
venv/lib64/python3.8/site-packages/urllib3/util/wait.py:146: in wait_for_read
    return wait_for_socket(sock, read=True, timeout=timeout)


sock = <socket.socket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
read = True, write = False, timeout = 0.0


def poll_wait_for_socket(sock, read=False, write=False, timeout=None):
    if not read and not write:
        raise RuntimeError("must specify at least one of read=True, write=True")
    mask = 0
    if read:
        mask |= select.POLLIN
    if write:
        mask |= select.POLLOUT
    poll_obj = select.poll()

  poll_obj.register(sock, mask)
E       ValueError: file descriptor cannot be a negative integer (-1)


venv/lib64/python3.8/site-packages/urllib3/util/wait.py:99: ValueError
```

RP link:  https://red.ht/3XAuhHa

**Comment by rachael-george** [comment] 2023-01-24 11:28
@OdedViner Do you think this issue would be fixed by https://github.com/red-hat-storage/ocs-ci/pull/6959

**Comment by am-agrawa** [comment] 2023-06-15 08:07
Assigned to Elena after discussion.

**Comment by ebondare** [comment] 2023-08-24 08:44
It looks like the issue was indeed solved by https://github.com/red-hat-storage/ocs-ci/pull/6959 as no more such failures were reported after the fix was merged. @am-agrawa I think we can close this issue, what do you think?

**Comment by am-agrawa** [comment] 2023-08-24 08:49
> It looks like the issue was indeed solved by #6959 as no more such failures were reported after the fix was merged. @am-agrawa I think we can close this issue, what do you think?

I am not sure. If the test is passing consistently, we can close it.

**Comment by ebondare** [comment] 2023-08-29 10:44
I retested test_clone_pvc on disconnected cluster https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/28697/, it passed. I think we can close the issue.

**Comment by ebondare** [comment] 2023-08-29 11:23
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/28715/consoleFull another run without any issues with closing browser

**Comment by am-agrawa** [comment] 2023-11-28 13:11
@ebondare @sidhant-agrawal Is this issue reproducible or we can close it?

**Closed** 2024-03-26 09:02 UTC
Labels: ui_automation, Squad/Green, lifecycle/keepalive
