### ISSUE TITLE
In tier1 of post OCP upgrade, the config.ENV_DATA['ocs_version'] is N+1 instead of N

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#3242] opened 2020-11-01 15:07 UTC
As seen in `ocs-ci results for OCS4-6-Downstream-OCP4-6-VSPHERE-IPI-1AZ-RHCOS-VSAN-3M-3W-tier1 (BUILD ID: v4.6.0-148.ci RUN ID: 1603957359)` - http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j024ai3c33-uo/j024ai3c33-uo_20201030T125655/logs/run-1604206959-config.yaml 
This run is OCS 4.5.2 with upgrade of OCP from 4.5 to 4.6.
Post OCP upgrade, the OCS version in config.ENV_DATA['ocs_version']  is 4.6 instead of 4.5.

This causes failures in tests that check this value, like the setup phase of MCG tests, which adjust the Noobaa endpoint with the corresponding CR, as described here:

```
The Noobaa endpoints minCount and maxCount values are being changed prior to the MCG test cases. These values are being modified in either the Noobaa CR if the OCS cluster version is lower than 4.6 or in the StorageCluster CR, if the cluster version is 4.6 or above.

From the test logs, it's noticeable that the minCount and maxCount are being changed via the StorageCluster CR, which is not the correct method, since the OCS version is 4.5:

15:48:07 - MainThread - ocs_ci.ocs.ocp - INFO - Command: patch storagecluster ocs-storagecluster -n openshift-storage -p '{"spec":{"multiCloudGateway":{"endpoints":{"minCount":2}}}}' --type merge
15:48:07 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig patch storagecluster ocs-storagecluster -n openshift-storage -p '{"spec":{"multiCloudGateway":{"endpoints":{"minCount":2}}}}' --type merge
15:48:08 - MainThread - tests.conftest - INFO - Changing maximum Noobaa endpoints to 2
15:48:08 - MainThread - ocs_ci.ocs.ocp - INFO - Command: patch storagecluster ocs-storagecluster -n openshift-storage -p '{"spec":{"multiCloudGateway":{"endpoints":{"maxCount":2}}}}' --type merge
15:48:08 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-storage --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig patch storagecluster ocs-storagecluster -n openshift-storage -p '{"spec":{"multiCloudGateway":{"endpoints":{"maxCount":2}}}}' --type merge


The OCS version is fetched from config.ENV_DATA['ocs_version'].
I looked at the run config post the OCP upgrade and saw the the value of this key is 4.6:

http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j024ai3c33-uo/j024ai3c33-uo_20201030T125655/logs/run-1604206959-config.yaml

ENV_DATA:
  ...
  ocs_version: '4.6'
```

**Comment by petr-balogh** [comment] 2020-11-02 08:35
I found the issue. It's actually our jenkins job settings.  In upgrade jobs, we do change  --ocs-version x.y  for the tier1 run after upgrade we change  --ocs-version to the one which is defined in our parameter UPGRADE_OCS_VERSION.   So we will need to in our upgrade specific runs pick proper version as it can break the logic as we can see.  But it's not a bug so closing it. We will need to highlight it more for people who is scheduling OCP upgrade jobs to properly pick also UPGRADE_OCS_VERSION parameter. Or I can try to fix it in the job itself, that if we do not run ocs upgrade we will not change the version for run after upgrade which will be more error prone.

**Closed** 2020-11-02 08:36 UTC
Labels: High Priority, bug

**Comment by petr-balogh** [comment] 2020-11-02 09:03
@ebenahar FYI this should fix the issue from jenkins job point of view and should not change the version of OCS next time if we do not run ocs upgrade in that upgrade execution.

https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/385
