### ISSUE TITLE
test_respin_mcg_pod_and_check_data_integrity_crd  need to be skipped in AWS-IPI-KMS_THALES until bug 2165907 is resolved

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#7870] opened 2023-06-20 15:25 UTC
Bug: https://bugzilla.redhat.com/show_bug.cgi?id=2165907#c7

We need to skip the test "test_respin_mcg_pod_and_check_data_integrity_crd" for AWS-IPI-KMS-THALES platform until above mentioned bug is resolved. The intention is to avoid the test causing the failure and hence causing other tests to fail as well because of Noobaa db pod CLBO

**Comment by sagihirshfeld** [comment] 2023-07-12 12:26
Several local attempts to reproduce with the same configuration haven't shown any errors so far. 

At first I figured that maybe the issue happens only after certain tests before `test_respin_mcg_pod_and_check_data_integrity_crd`, but in the original run where this happened (https://url.corp.redhat.com/54d0e87) only `test_delete_noobaa_resources` was ran before, and since it's just respinning noobaa pods this shouldn't be the cause.

If future CI runs in this configuration don't show this error I suggest closing this this issue and BZ.

**Comment by tiffanyn108** [comment] 2023-08-02 15:32
Sagi to close if not seen in recent run.

**Closed** 2023-11-22 15:19 UTC
Labels: High Priority, MCG, Squad/Red
