### ISSUE TITLE
namespace bucket tests fail when the cluster is not deployed on aws

### ISSUE THREAD

**Issue by bernerhat** [red-hat-storage/ocs-ci#3328] opened 2020-11-16 13:06 UTC
When trying to set up the target bucket for namespace bucket tests the region used to create the target bucket is the region of the cluster and since the cluster is deployed over a different platform than aws the cluster's region does not exist in aws.

**Comment by MeridianExplorer** [comment] 2021-01-11 09:35
Duplicate of #2774

**Closed by MeridianExplorer** 2021-01-11 09:35 UTC
Labels: High Priority, MCG, bug
