### ISSUE TITLE
TestAMQBasics.test_install_amq_scale is failing

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3372] opened 2020-11-20 05:18 UTC
Test case is failing in 4.6 rc2 build with time out error:
Console logs: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/14757/

``` self = <ocs_ci.utility.utils.TimeoutSampler object at 0x7efd7746ec18>

    def __iter__(self):
        if self.start_time is None:
            self.start_time = time.time()
        while True:
            self.last_sample_time = time.time()
            try:
                yield self.func(*self.func_args, **self.func_kwargs)
            except Exception as ex:
                msg = f"Exception raised during iteration: {ex}"
                logging.error(msg)
            if self.timeout < (time.time() - self.start_time):
>               raise self.timeout_exc_cls(*self.timeout_exc_args)
E               ocs_ci.ocs.exceptions.TimeoutExpiredError: Timed Out: (900,)

ocs_ci/utility/utils.py:828: TimeoutExpiredError

```

**Comment by SvetlanaRedHat** [comment] 2020-12-01 20:16
I tested loccaly and did not find any error. going to run a jenkins job and save the cluster for local debug.

**Comment by SvetlanaRedHat** [comment] 2020-12-07 05:29
The issue is not reproducable in locally.
closing this for now, will keep an eye on the jenkins cluster deployement jobs

**Comment by tiffanyn108** [comment] 2020-12-14 19:38
Re-open:  Seen the same failure in recent scale testing.
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15539/testReport/junit/tests.e2e.scale.test_scale_amq/TestAMQBasics/test_install_amq_scale_CephBlockPool_/

**Comment by SvetlanaRedHat** [comment] 2021-01-07 16:40
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16100/ deployed a new cluster to run again

**Comment by ramkiperiy** [comment] 2021-04-22 04:21
Added SKIP marker in the TC, while fixing the problem make sure to remove the skip marker.
https://github.com/red-hat-storage/ocs-ci/pull/4165

**Comment by ramkiperiy** [comment] 2021-09-08 15:39
Closing this issue, since we are planning to re-work on this test

**Closed by ramkiperiy** 2021-09-08 15:39 UTC
Labels: TestCase failing, scale, Low Priority, Squad/Orange
