### ISSUE TITLE
test_recovery_from_volume_deletion failed with failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed"

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#6723] opened 2022-12-07 20:08 UTC
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7051/295489/295504/295507/log
Run ID: 1670222569
Test Case: test_recovery_from_volume_deletion
ODF Build: 4.12.0-125
OCP Version: 4.12
Job name: VSPHERE6 UPI 1AZ RHCOS LOWERREQ VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6298/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/vavuthulwreq-t4a/vavuthulwreq-t4a_20221205T051247/logs/

Failure Details:
```
Message: failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed"
Type: None

Text:
def finalizer():
        if not skipped:
            try:
                teardown = config.RUN["cli_params"]["teardown"]
                skip_ocs_deployment = config.ENV_DATA["skip_ocs_deployment"]
                ceph_cluster_installed = config.RUN.get("cephcluster")
                if not (
                    teardown
                    or skip_ocs_deployment
                    or mcg_only_deployment
                    or not ceph_cluster_installed
                ):
                    if "test_add_capacity" in node.name:
                        ceph_health_check(
                            namespace=config.ENV_DATA["cluster_namespace"]
                        )
                        log.info(
                            "Ceph health check passed at teardown. (After Add capacity "
                            "TC we allow more re-tries)"
                        )
                    else:
>                       ceph_health_check_base()

tests/conftest.py:1442: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

namespace = 'openshift-storage'

    def ceph_health_check_base(namespace=None):
        """
        Exec `ceph health` cmd on tools pod to determine health of cluster.
    
        Args:
            namespace (str): Namespace of OCS
                (default: config.ENV_DATA['cluster_namespace'])
    
        Raises:
            CephHealthException: If the ceph health returned is not HEALTH_OK
            CommandFailed: If the command to retrieve the tools pod name or the
                command to get ceph health returns a non-zero exit code
        Returns:
            boolean: True if HEALTH_OK
    
        """
        # Import here to avoid circular loop
        from ocs_ci.ocs.cluster import is_ms_consumer_cluster
        from ocs_ci.ocs.managedservice import patch_consumer_toolbox
    
        namespace = namespace or config.ENV_DATA["cluster_namespace"]
        run_cmd(
            f"oc wait --for condition=ready pod "
            f"-l app=rook-ceph-tools "
            f"-n {namespace} "
            f"--timeout=300s"
        )
        ceph_health_cmd = create_ceph_health_cmd(namespace)
        try:
            health = run_cmd(ceph_health_cmd)
        except CommandFailed as ex:
            if "RADOS permission error" in str(ex) and is_ms_consumer_cluster():
                log.info("Patch the consumer rook-ceph-tools deployment")
                patch_consumer_toolbox()
                # get the new tool box pod since patching creates the new tool box pod
                ceph_health_cmd = create_ceph_health_cmd(namespace)
                health = run_cmd(ceph_health_cmd)
            else:
                raise ex
    
        if health.strip() == "HEALTH_OK":
            log.info("Ceph cluster health is HEALTH_OK.")
            return True
        else:
>           raise CephHealthException(f"Ceph cluster health is not OK. Health: {health}")
E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed

ocs_ci/utility/utils.py:2101: CephHealthException
```

**Comment by ebenahar** [comment] 2022-12-07 20:22
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/7051/295489/295504/295507/log
Run ID: 1670222569
Test Case: test_recovery_from_volume_deletion
Error Message: failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed"

**Comment by ebenahar** [comment] 2022-12-07 22:44
This issue was encountered once again.
Run details:

URL: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#OCS/launches/362/6596/271263/271282/271286/log
Run ID: 1669404527
Test Case: test_recovery_from_volume_deletion
ODF Build: 4.12.0-116
OCP Version: 4.12
Job name: VSPHERE6 UPI Disconnected 1AZ RHCOS VSAN 3M 3W tier4a
Jenkins job: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6134/
Logs URL: http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-001vud1cs33-t4a/j-001vud1cs33-t4a_20221125T174052/logs/
Error Message: ```failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 daemons have recently crashed"```

**Comment by sagihirshfeld** [comment] 2022-12-08 19:33
I also encountered similar failures while analyzing red-squad failures:

URL: [https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/368/6856/284469/284491/284496/log](url)
Run ID: 1669934735
Test Case: test_noobaa_service_mon_after_ocs_upgrade
ODF Build: 4.9.13 - Confirmed in the oc-must-gather logs.
OCP Version: 4.9 - Assumed to be before the upgrade to 4.12 since OCS is confirmed to be pre-upgrade during the test. Couldn't verify for certain in the oc-must-gather logs.
Job name: AZURE IPI 3AZ RHCOS 3M 3W upgrade-ocp
Jenkins job: [https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6234/](url)
Logs URL: [http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-168zi3c33-uo/j-168zi3c33-uo_20221130T153129/logs/](url)
Error Message: `failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 2 daemons have recently crashed`

URL: [https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/367/6876/285473/285495/285500/log](url)
Run ID: 1669805511
Test Case: test_noobaa_service_mon_after_ocs_upgrade
ODF Version: 4.10 / 4.12. Couldn't check for certain due to the absence of oc-must-gather logs.
OCP Version: 4.10 / 4.11. Couldn't check for certain due to the absence of oc-must-gather logs.
Job name: AZURE IPI 3AZ RHCOS 3M 3W upgrade-ocp
Jenkins job: [https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6217/](url)
Logs URL: [http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-166zi3c33-uo/j-166zi3c33-uo_20221130T094248/logs/](url)
Error Message: `failed on teardown with "ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1 clients failing to respond to capability release; 1 MDSs report slow requests`

Additional (red-squad unrelated) tests seemed to fail with similar errors in these two runs.

**Comment by am-agrawa** [comment] 2023-02-20 10:56
> Test Case:

This test case is different than the actually reported as part of this github issue.

**Comment by yitzhak12** [comment] 2023-02-21 16:37
I didn't see this error in the recent runs. I think that the pr @DanielOsypenko raised https://github.com/red-hat-storage/ocs-ci/pull/6725 may fix the issue. 
I am working on another minor fix related to the test above https://github.com/red-hat-storage/ocs-ci/pull/7144.

**Comment by yitzhak12** [comment] 2023-02-22 11:39
From what I see in the run https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/21297/console, the function `wait_for_silence_ceph_osd_crash_warning` works properly. So there could be another issue with the osd crash, or the crash warning appeared after more than 15 minutes.

**Comment by yitzhak12** [comment] 2023-02-22 11:44
IMO we can close this issue or wait another week to see if this error does not appear and then close it.
@am-agrawa @ebenahar @prsurve WDYT?

**Comment by am-agrawa** [comment] 2023-02-22 14:44
> IMO we can close this issue or wait another week to see if this error does not appear and then close it. @am-agrawa @ebenahar @prsurve WDYT?

Let's wait for the new runs and if we don't hit this issue, we can close it.

**Comment by pintojoy** [comment] 2023-04-20 16:01
Observing this issue with https://url.corp.redhat.com/6e21d85

**Comment by yitzhak12** [comment] 2023-04-23 13:34
@pintojoy I looked at the test you mentioned and saw that the error is different: https://reportportal-ocs4.apps.ocp-c1.prod.psi.redhat.com/ui/#ocs/launches/426/10343/458809/458824/458827/log?logParams=history%3D458827%26page.page%3D1: 

> E           ocs_ci.ocs.exceptions.CephHealthException: Ceph cluster health is not OK. Health: HEALTH_WARN 1/3 mons down, quorum b,c; 2 daemons have recently crashed

Something went wrong after running the ocs-osd-removal job. 
I saw in the node describe logs http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/j-286vuf1cs36-t4a/j-286vuf1cs36-t4a_20230405T205353/logs/failed_testcase_ocs_logs_1680731232/test_recovery_from_volume_deletion_ocs_logs/ocs_must_gather/quay-io-rhceph-dev-ocs-must-gather-sha256-9f7b97857662912db3a1da710af2ab27f71291fd8edb4c5274992e27a12e0377/cluster-scoped-resources/oc_output/desc_nodes, that the worker node `compute-1` is in NodeReady state: 

> Events:

>   Type    Reason                   Age                From     Message
>   ----    ------                   ----               ----     -------
>   Normal  NodeHasSufficientMemory  98s (x9 over 94m)  kubelet  Node compute-1 status is now: NodeHasSufficientMemory
>   Normal  NodeHasNoDiskPressure    98s (x9 over 94m)  kubelet  Node compute-1 status is now: NodeHasNoDiskPressure
>   Normal  NodeHasSufficientPID     98s (x9 over 94m)  kubelet  Node compute-1 status is now: NodeHasSufficientPID
>   Normal  NodeReady                98s (x2 over 93m)  kubelet  Node compute-1 status is now: NodeReady

Probably that's the reason for the Ceph health error.

**Comment by yitzhak12** [comment] 2023-04-23 14:14
Anyway, we need to backport the pr https://github.com/red-hat-storage/ocs-ci/pull/7144 to the previous versions: 4.12, 4.11, 4.10, and 4.9.

**Comment by yitzhak12** [comment] 2023-06-04 09:46
I backported the pr https://github.com/red-hat-storage/ocs-ci/pull/7144 to the previous versions: 4.12, 4.11, 4.10, and 4.9.
Now it should work fine.

**Closed** 2023-06-04 09:54 UTC
Labels: TestCase failing, Squad/Brown
