### ISSUE TITLE
test_multiregion_mirror fails with error: failed on setup with "TypeError: run() got multiple values for keyword argument 'shell'"

### ISSUE THREAD

**Issue by mashetty330** [red-hat-storage/ocs-ci#7475] opened 2023-04-17 04:45 UTC
https://url.corp.redhat.com/7be18f2

**Comment by sagihirshfeld** [comment] 2023-05-09 12:42
This is a duplicate of https://github.com/red-hat-storage/ocs-ci/issues/7263 that was fixed on March 13th

**Closed by sagihirshfeld** 2023-05-09 12:42 UTC
Labels: MCG, Squad/Red
