### ISSUE TITLE
RDR ODF deployment failure when trying to get cephblockpool from passive hub cluster

### ISSUE THREAD

**Issue by Shrivaibavi** [red-hat-storage/ocs-ci#9500] opened 2024-03-18 06:36 UTC
Description:
-------------------
The script was trying to find cephblockpool on passive hub cluster

```
2024-03-15 16:20:45  E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc get CephBlockPool -n openshift-storage -o=jsonpath='{.items[?(@.metadata.ownerReferences[*].kind=="StorageCluster")].spec.mirroring.enabled}'.
2024-03-15 16:20:45  E               Error is error: the server doesn't have a resource type "CephBlockPool"
2024-03-15 16:20:45  
2024-03-15 16:20:45  ocs_ci/utility/utils.py:686: CommandFailed

2024-03-15 16:20:44  10:50:44 - MainThread - ocs_ci.utility.utils - ERROR - C[sraghave-active] - Command oc get CephBlockPool -n openshift-storage -o=jsonpath='{.items[?(@.metadata.ownerReferences[*].kind=="StorageCluster")].spec.mirroring.enabled}' execution failed on cluster sraghave-passih 
```
https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-rdr-setup/635/console

Actual Results:
----------------------
The script was trying to find cephblockpool on passive cluster

Expected Results:
--------------------------
The above command for cephblockpool shouldn't run on hub clusters(passive/active)

**Comment by dahorak** [comment] 2024-03-18 07:22
The active acm hub seems to be skipped, but not the passive: https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L2337-L2339
But I don't know the details there @shylesh and @clacroix12, could you please check it?

**Comment by shylesh** [comment] 2024-03-18 11:13
@Shrivaibavi this is not a bug but actually RDR specific code https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L2338 . RDR was never rewrote for active/passive use case. It still assumes only one ACM. Closing this as not a bug.

**Closed by shylesh** 2024-03-18 11:13 UTC
