### ISSUE TITLE
Travis failure: ERROR: InvocationError for command /home/travis/build/red-hat-storage/ocs-ci/.tox/collectonly/bin/py.test --collect-only tests (exited with code 3)

### ISSUE THREAD

**Issue by PrasadDesala** [red-hat-storage/ocs-ci#1748] opened 2020-03-30 12:53 UTC
Travis-CI build for PR #1692 fails with below error, 
https://travis-ci.org/github/red-hat-storage/ocs-ci/jobs/668727877?utm_medium=notification&utm_source=github_status

I could reproduce this issue locally as well when ran this patch with "-collect-only".

**Comment by petr-balogh** [comment] 2020-05-06 11:25
Not a bug as I described in comment here: https://github.com/red-hat-storage/ocs-ci/pull/1692#discussion_r420715496 .  This is really an issue in your PR as you cannot call any oc command in the test collection when your cluster doesn't have to run. You will need to do some check if cluster is running and if so then you can do this kind of skip based on running cluster otherwise you will need to skip this skipping for LSO.

Closing this.

**Closed by petr-balogh** 2020-05-06 11:25 UTC
Labels: bug
