### ISSUE TITLE
Missing jobs link from jenkins

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#1732] opened 2020-03-27 17:42 UTC
Nfs was not mounted so we have missing logs link

```
Martin Bukatovic

Hmm, this is interesting. I don't see logs referenced from this run: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/5999/

TASK [ocs-ci-nfs : Prepare directory for openshift installer.] *****************
Thursday 26 March 2020  14:48:10 +0000 (0:00:00.040)       0:02:54.985 ******** 
[WARNING]: Module remote_tmp /home/jenkins/.ansible/tmp did not exist and was
created with a mode of 0700, this may cause issues when running as another
user. To avoid this, create the remote_tmp dir with the correct permissions
manually
```

**Comment by dahorak** [comment] 2020-04-03 08:37
I'm not sure, what is the root cause here, because the [logs are available](http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-vu1cv33-ua/jnk-vu1cv33-ua_20200326T144518/) - just not listed in the Job description (without any obvious error message).

Please, if you will dig into similar issue again, link it here, so I'll have more data for debugging. Ideally if the job will be still running/the jenkins slave will exist.

**Comment by dahorak** [comment] 2021-06-02 13:01
There seems to be no other occurrence of this issue, so I think we can close this ticket. Please reopen it or create new one, if there will be any new problem.

**Closed by dahorak** 2021-06-02 13:01 UTC
Labels: team/ecosystem
