### ISSUE TITLE
test_multipart_upload_operations is failing on ODF 4.16 on IBM Power

### ISSUE THREAD

**Issue by Pooja-Soni78** [red-hat-storage/ocs-ci#9749] opened 2024-05-02 06:44 UTC
Following test case is failing on IBM Power - 
```
tests/functional/object/rgw/test_multipart_upload.py::TestS3MultipartUpload::test_multipart_upload_operations
```
Error being -
```
>               raise CommandFailed(
                    f"Error during execution of command: {masked_cmd}."
                    f"\nError is {masked_stderr}"
                )
E               ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n s3cli-ipsuit6e6u1pm exec s3cli-0 -- bash -c "apk add s3cmd".
E               Error is ERROR: Unable to lock database: Permission denied
E               ERROR: Failed to open apk database: Permission denied
E               command terminated with exit code 99

ocs_ci/utility/utils.py:686: CommandFailed
```

**Comment by Pooja-Soni78** [comment] 2024-05-02 06:45
Log - 
[test_multipart_upload_operations.log](https://github.com/red-hat-storage/ocs-ci/files/15184645/test_multipart_upload_operations.log)

**Comment by udaysk23** [comment] 2024-05-20 09:29
This issue is duplicate of #9715

**Closed by udaysk23** 2024-05-20 09:29 UTC
Labels: Squad/Red
