### ISSUE TITLE
Deployment of LSO 4.7 failed when creating local-storage-operator

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3441] opened 2020-11-29 16:25 UTC
Deployment of LSO 4.7 failed when creating a `local-storage-operator`. 
Here is a link to the deployment https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15154/.
Here is a snippet of the relevant logs: 

> 12:27:49 - MainThread - ocs_ci.deployment.deployment - INFO - Creating local-storage-operator
12:27:49 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc create -f /tmp/local_storage_operatorol8wyggo
12:27:50 - MainThread - ocs_ci.ocs.ocp - INFO - Waiting for a resource(s) of kind Pod identified by name '' using selector name=local-storage-operator at column name STATUS to reach desired condition Running
12:27:50 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-local-storage get Pod  -n openshift-local-storage --selector=name=local-storage-operator -o yaml
12:27:50 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were [], but we were waiting for all of them to be Running
12:27:50 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 3 seconds before next iteration
12:27:53 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-local-storage get Pod  -n openshift-local-storage --selector=name=local-storage-operator -o yaml

> 12:31:09 - MainThread - ocs_ci.ocs.ocp - INFO - status of  at column STATUS - item(s) were [], but we were waiting for all of them to be Running
12:31:09 - MainThread - ocs_ci.utility.utils - INFO - Going to sleep for 3 seconds before next iteration
12:31:12 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-local-storage get Pod  -n openshift-local-storage --selector=name=local-storage-operator -o yaml
12:31:22 - MainThread - ocs_ci.utility.utils - WARNING - Command stderr: Error from server (InternalError): an error on the server ("") has prevented the request from succeeding (get pods)

**Comment by ebenahar** [comment] 2020-11-29 17:23
@clacroix12 @prsurve is this somehow similar to https://github.com/red-hat-storage/ocs-ci/issues/2908?

**Comment by prsurve** [comment] 2020-11-30 03:18
Deployment job failed because LSO is using `channel: '4.7'` and that channel is not yet opened so until OCP 4.7 get's GAed we have to use `channel: '4.6'`

**Comment by petr-balogh** [comment] 2020-11-30 08:54
I thought that implementation @clacroix12 did suppose to work for any future non GAed OCP versions but maybe I am missing something.  Let's wait for Coady's input here.

@clacroix12 if you can take a look at this issue please.

**Comment by petr-balogh** [comment] 2020-12-01 16:00
@clacroix12 can you please do the deployment and see if we do see the 4.7 channel in package manifest for LSO for source: optional-operators?

I didn't have chance to take a look at this. Will be happy if you can take a look and in case it's not there to ask on aos-devel from else we can get 4.7 LSO non GAed version and describe how we got it for 4.6.

**Comment by petr-balogh** [comment] 2020-12-01 16:10
@clacroix12 as DC ECO is occupied ATM feel free to use LSO deployment over I3 on AWS for verification or testing. Thanks!

**Comment by clacroix12** [comment] 2020-12-02 16:47
I confirmed that the 4.7 channel is available after adding the optional operators catalogsource. I attempted to install the LSO via the UI after adding the optional operators catalogsource but it didn't install fully. The installPlan ended up stuck in the installing phase for some reason that I'm unable to determine.

**Comment by clacroix12** [comment] 2020-12-02 22:14
Seems like this is a product issue and not one with ocs-ci so i created a bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1903826

**Comment by petr-balogh** [comment] 2020-12-02 22:17
Thanks @clacroix12 , I don't see OCP must gather logs attached in BZ, can you collect one and add it there? Thanks

**Comment by clacroix12** [comment] 2020-12-02 23:57
> Thanks @clacroix12 , I don't see OCP must gather logs attached in BZ, can you collect one and add it there? Thanks

must gather logs have been uploaded to our NFS share and linked in the BZ, thanks!

**Comment by clacroix12** [comment] 2021-01-08 19:47
From 4.7 onwards non-GA LSO deployments require brew registry access set in the pull secret as well as an updated ImageContentSourcePolicy. I have verified this locally, updated the pull secret the ecosystem team has in our drive as well as the pull secret in jenkins. I've raised a PR to update the ICSP yaml which will close this issue out.

**Closed** 2021-01-11 18:48 UTC
