### ISSUE TITLE
Performance test failure test_small_file_workload.py

### ISSUE THREAD

**Issue by wusui** [red-hat-storage/ocs-ci#3580] opened 2020-12-22 00:54 UTC
Sample output;

'cmd = ['oc', '-n', 'elastic-system', 'apply', '-f', 'ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml']
secrets = None, timeout = 600, ignore_error = False, kwargs = {}
masked_cmd = 'oc -n elastic-system apply -f ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml'
completed_process = CompletedProcess(args=['oc', '-n', 'elastic-system', 'apply', '-f', 'ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.ya...y one of None, NoneOnDryRun\n* webhooks[7].admissionReviewVersions: Required value: must specify one of v1, v1beta1\n')
masked_stdout = 'namespace/elastic-system unchanged\nserviceaccount/elastic-operator unchanged\nsecret/elastic-webhook-server-cert unc...o/elastic-operator unchanged\nservice/elastic-webhook-server unchanged\nstatefulset.apps/elastic-operator configured\n'
masked_stderr = 'The ValidatingWebhookConfiguration "elastic-webhook.k8s.elastic.co" is invalid: \n* webhooks[0].sideEffects: Required...fy one of None, NoneOnDryRun\n* webhooks[7].admissionReviewVersions: Required value: must specify one of v1, v1beta1\n'

.           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n elastic-system apply -f ocs_ci/templates/app-pods/eck.1.3.1-all-in-one.yaml.
E           Error is The ValidatingWebhookConfiguration "elastic-webhook.k8s.elastic.co" is invalid: 
E           * webhooks[0].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[0].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[1].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[1].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[2].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[2].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[3].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[3].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[4].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[4].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[5].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[5].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[6].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[6].admissionReviewVersions: Required value: must specify one of v1, v1beta1
E           * webhooks[7].sideEffects: Required value: must specify one of None, NoneOnDryRun
E           * webhooks[7].admissionReviewVersions: Required value: must specify one of v1, v1beta1

Command executed was:
run-ci -m performance --cluster-name lr4-wusui-scale --cluster-path /home/wusui/ocs-ci tests/e2e/performance/test_small_file_workload.py

I have must-gather output and the full output of the command

.
.

**Comment by wusui** [comment] 2020-12-22 00:57
This may be the same issue that is seen in 3575

**Comment by Avilir** [comment] 2020-12-22 07:57
@wusui , yes this is duplicate of #3575 , and it fixed with #3576

**Closed by Avilir** 2020-12-22 07:57 UTC
Labels: performance
