### ISSUE TITLE
 tests.functional.object.mcg.test_pv_pool.TestPvPool.test_pvpool_resource_modifications[bucketclass_dict0]

### ISSUE THREAD

**Issue by gayathrimenath-ibm** [red-hat-storage/ocs-ci#10895] opened 2024-11-20 14:05 UTC
```
ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n s3cli-93hfwpynn3r8x rsh s3cli-0 sh -c "AWS_CA_BUNDLE=/cert/service-ca.crt AWS_ACCESS_KEY_ID=***** AWS_SECRET_ACCESS_KEY=***** aws s3 --endpoint=***** cp test_pvpool_resource_modifications[bucketclass_dict0]/origin/test-obj-0 s3://oc-bucket-b674603e4e0940f7a1c7f1f7baf6d8".
Error is upload failed: test_pvpool_resource_modifications[bucketclass_dict0]/origin/test-obj-0 to s3://oc-bucket-b674603e4e0940f7a1c7f1f7baf6d8/test-obj-0 An error occurred (InvalidBucketState) when calling the PutObject operation: The request is not valid with the current state of the bucket.
command terminated with exit code 1
```
Tier2 testcase test_pvpool_resource_modifications
URL:  https://url.corp.redhat.com/d434244

**Comment by udaysk23** [comment] 2024-11-29 06:05
Closing this issue as duplicate of #8270

**Closed by udaysk23** 2024-11-29 06:05 UTC
Labels: Squad/Red
