### ISSUE TITLE
Deployment fails on Not enough worker nodes: 2 to label: 3 or taint: 0!

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#956] opened 2019-10-31 14:43 UTC
## Description of the problem

When I try to deploy OCS cluster via ocs-ci (using default downstream config in AWS), the deployment fails with `Not enough worker nodes: 2 to label: 3 or taint: 0!` exception.

## Version

ocs-ci: 55f69f1

cluster:

```
cluster channel: stable-4.2
cluster version: 4.2.0-0.nightly-2019-10-30-152749
cluster image: registry.svc.ci.openshift.org/ocp/release@sha256:08754f5f48452edb6feed48b16b4a4e53804c33df47264f60b5c42a4be9093c7

storage namespace openshift-cluster-storage-operator
image quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3e1089ccb42d3373e9b1595cd47c9c4fd4f629f94f5c3edc2c6a4cf85db5f575
 * quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3e1089ccb42d3373e9b1595cd47c9c4fd4f629f94f5c3edc2c6a4cf85db5f575
```

No OCS component is listed, because OCS was not installed.

## Steps to reproduce

Use ocs-ci to install OCS cluster with default configuration:

```
$ run-ci --cluster-path ~/data/cluster-2019-10-31.1 --cluster-name mbukatov-ocsqe --deploy -m deployment
```

## Actual Results

The installation fails on:

```
self = <ocs_ci.deployment.aws.AWSIPI object at 0x7f35feacd990>

    def label_and_taint_nodes(self):
        """
        Label and taint worker nodes to be used by OCS operator
        """
    
        nodes = ocp.OCP(kind='node').get().get('items', [])
        worker_nodes = [
            node for node in nodes if "node-role.kubernetes.io/worker"
            in node['metadata']['labels']
        ]
        if not worker_nodes:
            raise UnavailableResourceException("No worker node found!")
        to_label = config.DEPLOYMENT.get('ocs_operator_nodes_to_label', 3)
        to_taint = config.DEPLOYMENT.get('ocs_operator_nodes_to_taint', 0)
        worker_count = len(worker_nodes)
        if worker_count < to_label or worker_count < to_taint:
            logger.info(f"All nodes: {nodes}")
            logger.info(f"Worker nodes: {worker_nodes}")
            raise UnavailableResourceException(
>               f"Not enough worker nodes: {worker_count} to label: "
                f"{to_label} or taint: {to_taint}!"
            )
E           ocs_ci.ocs.exceptions.UnavailableResourceException: Not enough worker nodes: 2 to label: 3 or taint: 0!

ocs_ci/deployment/deployment.py:132: UnavailableResourceException
```

And OCS is not installed on OCP cluster.

When I check number of worker noted, I see only 2:

```
$ oc get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-134-141.us-east-2.compute.internal   Ready    worker   31m   v1.14.6+0ec926dcc
ip-10-0-142-205.us-east-2.compute.internal   Ready    master   36m   v1.14.6+0ec926dcc
ip-10-0-144-66.us-east-2.compute.internal    Ready    master   36m   v1.14.6+0ec926dcc
ip-10-0-159-185.us-east-2.compute.internal   Ready    worker   31m   v1.14.6+0ec926dcc
ip-10-0-163-198.us-east-2.compute.internal   Ready    master   36m   v1.14.6+0ec926dcc
```

## Expected Results

I see 3 worker nodes, so that OCS is installed.

**Comment by mbukatov** [comment] 2019-10-31 15:57
I retried and the deployment finished. I see 3 worker nodes as expected, and OCS is installed:

```
$ oc get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-130-225.us-east-2.compute.internal   Ready    worker   27m   v1.14.6+0ec926dcc
ip-10-0-135-249.us-east-2.compute.internal   Ready    master   33m   v1.14.6+0ec926dcc
ip-10-0-151-220.us-east-2.compute.internal   Ready    worker   27m   v1.14.6+0ec926dcc
ip-10-0-159-157.us-east-2.compute.internal   Ready    master   33m   v1.14.6+0ec926dcc
ip-10-0-163-225.us-east-2.compute.internal   Ready    worker   27m   v1.14.6+0ec926dcc
ip-10-0-168-39.us-east-2.compute.internal    Ready    master   33m   v1.14.6+0ec926dcc
```

So it looks like an infra glitch.

**Comment by petr-balogh** [comment] 2019-11-01 10:01
In the ocs-ci we are checking the number of worker nodes to be at least 3 if we need to label 3 nodes. This looks like some temporary issue which I haven't seen before and it's not bug in ocs-ci but probably some issue with your OCP deployment. 

As you listed just 2 worker nodes available:
```
 oc get nodes
NAME                                         STATUS   ROLES    AGE   VERSION
ip-10-0-134-141.us-east-2.compute.internal   Ready    worker   31m   v1.14.6+0ec926dcc
ip-10-0-142-205.us-east-2.compute.internal   Ready    master   36m   v1.14.6+0ec926dcc
ip-10-0-144-66.us-east-2.compute.internal    Ready    master   36m   v1.14.6+0ec926dcc
ip-10-0-159-185.us-east-2.compute.internal   Ready    worker   31m   v1.14.6+0ec926dcc
ip-10-0-163-198.us-east-2.compute.internal   Ready    master   36m   v1.14.6+0ec926dcc
```
This is expected behavior to fail if by default there should be 3 worker nodes.

Closing this issue as this is expected behavior of ocs-ci.

**Closed by petr-balogh** 2019-11-01 10:01 UTC
Labels: bug
