### ISSUE TITLE
Installation fails on pods "alertmanager-main-0" not found

### ISSUE THREAD

**Issue by mbukatov** [red-hat-storage/ocs-ci#929] opened 2019-10-23 10:29 UTC
When I use ocs-ci to deploy OCS cluster in AWS (with default downstream configuration), the deployment fails on  `pods "alertmanager-main-0" not found` error.

That said, I see that the alermanager pods are running:

```
$ oc get pods --all-namespaces | grep alertmanager
openshift-monitoring                                    alertmanager-main-0                                                   3/3     Running     0          49m
openshift-monitoring                                    alertmanager-main-1                                                   3/3     Running     0          49m
openshift-monitoring                                    alertmanager-main-2                                                   3/3     Running     0          49m
```

We need to look into this to see if this is a ocs-ci or a product bug. This problem could also affects results in CI in a negative way.

See full traceback in gist: https://gist.github.com/mbukatov/9287daffc1bb79d225946d45b64feb27

ocs-ci version: commit fba3174

**Comment by mbukatov** [comment] 2019-10-23 10:40
This could be a product bug, but so far there is no evidence for this hypothesis.

**Comment by gklein** [comment] 2019-11-17 11:54
It was reproduced on my system today

```12:16:55 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get ConfigMap cluster-monitoring-config -n openshift-monitoring -o yaml
12:16:56 - MainThread - ocs_ci.ocs.monitoring - INFO - Successfully created configmap cluster-monitoring-config
12:16:56 - MainThread - ocs_ci.deployment.deployment - INFO - Waiting 30 seconds...
12:17:26 - MainThread - ocs_ci.ocs.ocp - INFO - Waiting for a resource(s) of kind Pod identified by name 'alertmanager-main-0' and selector None to reach desired condition Running
12:17:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
12:17:26 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
12:17:27 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 was Terminating, but we were waiting for Running
12:17:30 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
12:17:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
12:17:32 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/openshift/origin-must-gather will be used.
12:17:32 - MainThread - ocs_ci.ocs.utils - INFO - OCS logs will be placed in location /tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocp_must_gather
12:17:32 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig adm must-gather --image=quay.io/openshift/origin-must-gather --dest-dir=/tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocp_must_gather
12:22:37 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/openshift/origin-must-gather will be used.
12:22:37 - MainThread - ocs_ci.ocs.utils - INFO - OCS logs will be placed in location /tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocp_must_gather
12:22:37 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig adm must-gather --image=quay.io/openshift/origin-must-gather --dest-dir=/tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocp_must_gather -- /usr/bin/gather_service_logs worker
12:22:55 - MainThread - ocs_ci.ocs.utils - INFO - Must gather image: quay.io/rhceph-dev/ocs-must-gather will be used.
12:22:55 - MainThread - ocs_ci.ocs.utils - INFO - OCS logs will be placed in location /tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocs_must_gather
12:22:55 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig adm must-gather --image=quay.io/rhceph-dev/ocs-must-gather --dest-dir=/tmp/failed_testcase_ocs_logs_1573982922/deployment_ocs_logs/ocs_must_gather
ERROR                                                                                                                                                                [100%]

================================================================================== ERRORS ==================================================================================
____________________________________________________________________ ERROR at setup of test_deployment _____________________________________________________________________

request = <SubRequest 'cluster' for <Function test_deployment>>, log_cli_level = 'INFO'

    @pytest.fixture(scope="session", autouse=True)
    def cluster(request, log_cli_level):
        """
        This fixture initiates deployment for both OCP and OCS clusters.
        Specific platform deployment classes will handle the fine details
        of action
        """
        log.info(f"All logs located at {ocsci_log_path()}")

        teardown = config.RUN['cli_params']['teardown']
        deploy = config.RUN['cli_params']['deploy']
        factory = dep_factory.DeploymentFactory()
        deployer = factory.get_deployment()

        # Add a finalizer to teardown the cluster after test execution is finished
        if teardown:
            def cluster_teardown_finalizer():
                deployer.destroy_cluster(log_cli_level)
            request.addfinalizer(cluster_teardown_finalizer)
            log.info("Will teardown cluster because --teardown was provided")

        # Download client
        force_download = (
            config.RUN['cli_params'].get('deploy')
            and config.DEPLOYMENT['force_download_client']
        )
        get_openshift_client(force_download=force_download)

        if deploy:
            # Deploy cluster
>           deployer.deploy_cluster(log_cli_level)

ocs-ci/tests/conftest.py:723:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
ocs-ci/ocs_ci/deployment/deployment.py:85: in deploy_cluster
    self.deploy_ocs()
ocs-ci/ocs_ci/deployment/deployment.py:378: in deploy_ocs
    pods_list
ocs-ci/ocs_ci/ocs/resources/pod.py:868: in validate_pods_are_respinned_and_running_state
    helpers.wait_for_resource_state(pod, constants.STATUS_RUNNING)
ocs-ci/tests/helpers.py:87: in wait_for_resource_state
    condition=state, resource_name=resource.name, timeout=timeout
ocs-ci/ocs_ci/ocs/ocp.py:396: in wait_for_resource
    status = self.get_resource_status(resource_name)
ocs-ci/ocs_ci/ocs/ocp.py:498: in get_resource_status
    resource = self.get(resource_name=resource_name, out_yaml_format=False)
ocs-ci/ocs_ci/ocs/ocp.py:174: in get
    return self.exec_oc_cmd(command)
ocs-ci/ocs_ci/ocs/ocp.py:106: in exec_oc_cmd
    out = run_cmd(cmd=oc_cmd, secrets=secrets, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

cmd = ['oc', '-n', 'openshift-monitoring', '--kubeconfig', '/Users/gklein/cluster-path/auth/kubeconfig', 'get', ...], secrets = None, kwargs = {}
masked_cmd = 'oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring'
r = CompletedProcess(args=['oc', '-n', 'openshift-monitoring', '--kubeconfig', '/Users/gklein/cluster-path/auth/kubeconfig...monitoring'], returncode=1, stdout=b'', stderr=b'Error from server (NotFound): pods "alertmanager-main-0" not found\n')

    def run_cmd(cmd, secrets=None, **kwargs):
        """
        Run an arbitrary command locally

        Args:
            cmd (str): command to run

            secrets (list): A list of secrets to be masked with asterisks
                This kwarg is popped in order to not interfere with
                subprocess.run(**kwargs)

        Raises:
            CommandFailed: In case the command execution fails

        Returns:
            (str) Decoded stdout of command

        """
        masked_cmd = mask_secrets(cmd, secrets)
        log.info(f"Executing command: {masked_cmd}")
        if isinstance(cmd, str):
            cmd = shlex.split(cmd)
        r = subprocess.run(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.PIPE,
            **kwargs
        )
        log.debug(f"Command output: {r.stdout.decode()}")
        if r.stderr and not r.returncode:
            log.warning(f"Command warning: {mask_secrets(r.stderr.decode(), secrets)}")
        if r.returncode:
            raise CommandFailed(
>               f"Error during execution of command: {masked_cmd}."
                f"\nError is {mask_secrets(r.stderr.decode(), secrets)}"
            )
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring.
E           Error is Error from server (NotFound): pods "alertmanager-main-0" not found

ocs-ci/ocs_ci/utility/utils.py:410: CommandFailed
============================================================== 216 deselected, 1 error in 3385.51s (0:56:25) ===============================================================```

**Comment by mbukatov** [comment] 2019-11-18 13:42
I hit the issue again today (the traceback is the same as in my original gist or as shown in gklein's comment above, and as was the case in original report, the `alertmanager-main-0` pod was up and running when I were looking into what went wrong after failed installation.

**Comment by nehaberry** [comment] 2019-11-18 18:26
@mbukatov since the alertmanager pod finally comes in Running state, could it be an early timeout issue ? Maybe the alert manager pod took more than expected time to mount the CephFS PVC and come to running state ? Just a hunch .

**Comment by vasukulkarni** [comment] 2019-11-18 21:59
I have since this intermittently as well before.

**Comment by gklein** [comment] 2019-11-19 07:23
If we see this too often I suggest extending the waiting time for the alertmanager pod. 

I've added an extra 15 seconds wait in this PR:

https://github.com/red-hat-storage/ocs-ci/pull/1023

**Comment by gklein** [comment] 2019-11-20 08:58
I just stumble upon this issues again. 

```
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-monitoring --kubeconfig /Users/gklein/cluster-path/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring.
E           Error is Error from server (NotFound): pods "alertmanager-main-0" not found

ocs_ci/utility/utils.py:413: CommandFailed
============================================================== 240 deselected, 1 error in 2845.72s (0:47:25) ==============================================================
```

As soon as I checked the pod status it was already running:

```
> oc get pods -n openshift-monitoring   alertmanager-main-0
NAME                  READY   STATUS    RESTARTS   AGE
alertmanager-main-0   3/3     Running   0          2m
```

**Comment by petr-balogh** [comment] 2019-11-20 15:18
this is after increased timeout @gklein ?

**Comment by gklein** [comment] 2019-11-20 15:23
> this is after increased timeout @gklein ?

No, I was on the master branch here so is was tested without the change. 

I'll follow up on this now that the PR is merged with the 45 seconds wait.

**Comment by petr-balogh** [comment] 2019-12-14 14:54
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/3044/testReport/tests.ecosystem.deployment/test_deployment/test_deployment/ see this failed also with most likely related issue to this

**Comment by petr-balogh** [comment] 2020-01-06 11:34
```
21:15:24 - MainThread - ocs_ci.ocs.ocp - INFO - Waiting for a resource(s) of kind Pod identified by name 'alertmanager-main-0' using selector None at column name STATUS to reach desired condition Running
21:15:24 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:24 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:25 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was Terminating, but we were waiting for Running
21:15:28 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:28 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: alertmanager-main-0, Error: Error during execution of command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml.
Error is Error from server (NotFound): pods "alertmanager-main-0" not found

21:15:28 - MainThread - ocs_ci.ocs.ocp - ERROR - Number of attempts to get resource reached!
21:15:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:31 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:31 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was Pending, but we were waiting for Running
21:15:34 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:35 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:35 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was ContainerCreating, but we were waiting for Running
21:15:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:38 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:39 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was ContainerCreating, but we were waiting for Running
21:15:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:42 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:42 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was ContainerCreating, but we were waiting for Running
21:15:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:45 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:46 - MainThread - ocs_ci.ocs.ocp - INFO - status of alertmanager-main-0 at column STATUS was ContainerCreating, but we were waiting for Running
21:15:49 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
21:15:49 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring
21:15:49 - MainThread - tests.helpers - INFO - Pod alertmanager-main-0 reached state Running
```

I see from log that alertmanager pod is really terminating  during the deployment so it can happen that in the another call of get that the pod is missing for 1 second and then it will fail with the error described in this issue.  I think that my fix provided in https://github.com/red-hat-storage/ocs-ci/pull/1253 should fix this issue and make wait_for_resource function more stable as if we really wait for resource it shouldn't  fail if we still didn't reach the timeout.

**Comment by fbalak** [comment] 2020-03-02 09:46
I have encountered this issue:
```
(...)
08:45:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod prometheus-k8s-1 -n openshift-monitoring -o yaml
08:45:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod prometheus-k8s-1 -n openshift-monitoring
08:45:16 - MainThread - tests.helpers - INFO - Pod prometheus-k8s-1 reached state Running
08:45:16 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
08:45:17 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-1 -n openshift-monitoring -o yaml
08:45:17 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-2 -n openshift-monitoring -o yaml
08:45:17 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod prometheus-k8s-0 -n openshift-monitoring -o yaml
08:45:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod prometheus-k8s-1 -n openshift-monitoring -o yaml
08:45:18 - MainThread - ocs_ci.ocs.monitoring - INFO - Verify pvc are created
08:45:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get PersistentVolumeClaim  -n openshift-monitoring -o yaml
08:45:18 - MainThread - ocs_ci.ocs.monitoring - INFO - PVC list {'apiVersion': 'v1', 'items': [], 'kind': 'List', 'metadata': {'resourceVersion': '', 'selfLink': ''}}
08:45:18 - MainThread - ocs_ci.ocs.monitoring - INFO - Verified: Created PVCs are in Bound state.
08:45:18 - MainThread - ocs_ci.utility.utils - INFO - Executing command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml
08:45:18 - MainThread - ocs_ci.ocs.ocp - WARNING - Failed to get resource: alertmanager-main-0 of kind: Pod, selector: None, Error: Error during execution of command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml.
Error is Error from server (NotFound): pods "alertmanager-main-0" not found

08:45:18 - MainThread - ocs_ci.ocs.ocp - WARNING - Number of attempts to get resource reached!
(...)
        log.debug(f"Command output: {r.stdout.decode()}")
        if r.stderr and not r.returncode:
            log.warning(f"Command warning: {mask_secrets(r.stderr.decode(), secrets)}")
        if r.returncode and not ignore_error:
            raise CommandFailed(
>               f"Error during execution of command: {masked_cmd}."
                f"\nError is {mask_secrets(r.stderr.decode(), secrets)}"
            )
E           ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc -n openshift-monitoring --kubeconfig /home/jenkins/current-cluster-dir/openshift-cluster-dir/auth/kubeconfig get Pod alertmanager-main-0 -n openshift-monitoring -o yaml.
E           Error is Error from server (NotFound): pods "alertmanager-main-0" not found
```
With version:
ocs-operator.v4.3.0-ci.350

**Closed** 2020-04-16 09:27 UTC
Labels: bug
