### ISSUE TITLE
ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no pv deletion data in CSI logs

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#3524] opened 2020-12-14 20:00 UTC
Failure log: https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/15539/testReport/junit/tests.e2e.scale.test_pvc_creation_deletion_scale/TestPVCCreationDeletionScale/test_multiple_pvc_creation_deletion_scale_ReadWriteMany_cephfs_/

if loop_counter >= 3:
                    logging.info("Waited for more than 3mins still no data")
                    raise UnexpectedBehaviour(
>                       f"There is no pv deletion data in CSI logs for {no_data_list}"
                    )
E                   ocs_ci.ocs.exceptions.UnexpectedBehaviour: There is no pv deletion data in CSI logs for ['pvc-0a1fb4e2-03a6-488f-989a-cea0083b0a91', 'pvc-89cccb67-6664-4ee5-9892-fc1aeeb87f90', 'pvc-64116fca-67b7-49fc-be5f-7adc4b5ae12d', ...

**Comment by ramkiperiy** [comment] 2021-05-03 15:31
Duplicate of https://github.com/red-hat-storage/ocs-ci/issues/4042, closing this issue.

**Closed by ramkiperiy** 2021-05-03 15:31 UTC
Labels: TestCase failing, scale
