### ISSUE TITLE
Enhance failure message, when no tests were executed

### ISSUE THREAD

**Issue by vasukulkarni** [red-hat-storage/ocs-ci#4072] opened 2021-03-29 20:58 UTC
Following PR verification job is marked as failed:

https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-trigger-test-pr/422/

But if we look at the breakdown of pipelines, it failed during grafana reporter and continued to run the test and the test itself had no issues

```
+ python /home/jenkins/workspace/qe-deploy-ocs-cluster/scripts/python/grafana_reporter/main.py --user admin --update --filter-by buildurl=https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/1648/ --pause-before-upgrade=false --sta

ge-conf= --ocs-ci-repository=https://github.com/red-hat-storage/ocs-ci.git --yaml-text-config= --ocp-version=4.6 --email= --osd-size=100 --production-run=false --upgrade-ocs-version=4.6 --upgrade-test-path=tests/ --run-prepare-jslave=true --log-cluster-utilization=false --collect-logs=true --force-build-name=jnk-pr4060 --credentials-conf=vSphere-DC-CP_VC1 --jobs-repository=https://gitlab.cee.redhat.com/ocs/ocs4-jenkins.git --upgrade-ocs-registry-image= --run-install=true --report-upgrade-to-version=false --upgrade-test-mark-expression= --fips=false --ui-deploy=false --display-name= --flexy-private-conf-repository-branch= --test-path=tests/manage/z_cluster/test_coredump_check_for_ceph_daemon_crash.py --ocs-version=4.6 --flexy-private-conf-repository= --ignore-lock=true --run-teardown=true --ocs-registry-image= --external-rhcs-conf= --cluster-conf= --pause-before-teardown=false --ceph-debug=false --upgrade-ocp-image= --pause-before-test-execution=false --openshift-console-repository-branch=master --openshift-console-repository=https://github.com/openshift/console.git --description=Testing,PR, --lockable-resource= --test-mark-expression=tier1 --additional-pytest-params= --jobs-repository-branch=master --cluster-name=jnk-pr4060-b422 --live-stage-upgrade=false --run-test=true --upgrade-ocp-version=4.7 --live-deploy=false --report-portal=false --encryption-at-rest=false --ocp-installer-version= --test-name-expression= --upgrade=false --platform-conf=ocsci/vsphere_upi.yaml --ocs-ci-repository-branch=pr/4060 --collect-logs-on-success=true
/home/jenkins/workspace/qe-deploy-ocs-cluster@tmp/durable-98f0cc6d/script.sh: line 12: a,href=https://github.com/red-hat-storage/ocs-ci/pull/4060,target=_blank: No such file or directory
[Pipeline] echo
Caught exception during running reporter script. ERROR: hudson.AbortException: script returned exit code 1
[Pipeline] echo
Exception detail: script returned exit code 1
[Pipeline] echo
Exception is ignored because we do not want to break whole execution if
      something goes wrong in the reporter script. But if you see this
      message please contact someone from infra team to take a look.
[Pipeline] library
Only using first definition of library ocs4-jenkins
```

I think for such issues, we could send out an email to ocs-ecosystem-team and mark the job as pass so that users dont have to worry about the failure(since nothing actually failed in the test path)

**Comment by petr-balogh** [comment] 2021-03-30 14:32
The job didn't fail cause of reporter script.  As you see we are ignoring this error:
```
Exception is ignored because we do not want to break whole execution if
      something goes wrong in the reporter script. But if you see this
      message please contact someone from infra team to take a look.
```

The reason why this job failed is probably this:
https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/blob/master/jobs/pipelines/qe_deploy_ocs_cluster/Jenkinsfile#L700

```
$ wget http://magna002.ceph.redhat.com/ocsci-jenkins/openshift-clusters/jnk-pr4060-b422/jnk-pr4060-b422_20210329T151349/logs/test_results_1617030579.xml
$ grep -q -v ' tests="0"' test_results_1617030579.xml
$ echo $?
1
```

The message is not clear enough. @dahorak might improve logging for this in the job.
IIRC we added this to prevent the job to be succeeded if we ran 0 test cases.

So if you ran the verification and actual no test was triggered then this is expected behavior to prevent us to consider production jobs as passed if they didn't run any test.

@vasukulkarni if you think that we should allow such scenario then we can add extra parameter to PR validation job like:
ALLOW_ALL_TESTS_SKIPPED
Which can be then used for such testing and will not do our check:
```
grep -q -v ' tests="0"' ${testResultsFile}
```

**Comment by dahorak** [comment] 2021-03-31 07:40
I'll take care of the error message for situation when no tests are executed (changed the title of this issue accordingly).

**Comment by dahorak** [comment] 2021-03-31 09:13
Created [MR!595](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/595).

**Comment by dahorak** [comment] 2021-04-01 06:40
[MR!595](https://gitlab.cee.redhat.com/ocs/ocs4-jenkins/-/merge_requests/595) merged, closing this issue.

**Closed** 2021-04-01 06:40 UTC
Labels: High Priority
