### ISSUE TITLE
Adjust test_recovery_from_volume_deletion to run over LSO 

### ISSUE THREAD

**Issue by ebenahar** [red-hat-storage/ocs-ci#2206] opened 2020-06-01 11:51 UTC
As seen in https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/8265/testReport/tests.manage.z_cluster.nodes.test_disk_failures/TestDiskFailures/test_recovery_from_volume_deletion/, we need to adjust the test to run over LSO.

```
self = <tests.manage.z_cluster.nodes.test_disk_failures.TestDiskFailures object at 0x7fc63fd23e48>
nodes = <ocs_ci.ocs.platform_nodes.VMWareNodes object at 0x7fc66d332240>
pvc_factory = <function pvc_factory_fixture.<locals>.factory at 0x7fc65d287c80>
pod_factory = <function pod_factory_fixture.<locals>.factory at 0x7fc65d287b70>

    @bugzilla('1830702')
    @vsphere_platform_required
    @pytest.mark.polarion_id("OCS-2172")
    def test_recovery_from_volume_deletion(self, nodes, pvc_factory, pod_factory):
        """
        Test cluster recovery from disk deletion from the platform side.
        Based on documented procedure detailed in
        https://bugzilla.redhat.com/show_bug.cgi?id=1787236#c16
    
        """
        logger.info("Picking a PV which will be deleted from the platform side")
        osd_pvs = get_deviceset_pvs()
        osd_pv = random.choice(osd_pvs)
        osd_pv_name = osd_pv.name
        # get the claim name
        logger.info(f"Getting the claim name for OSD PV {osd_pv_name}")
        claim_name = osd_pv.get().get('spec').get('claimRef').get('name')
    
        # Get the backing volume name
        logger.info(f"Getting the backing volume name for PV {osd_pv_name}")
>       backing_volume = nodes.get_data_volumes(pvs=[osd_pv])[0]

tests/manage/z_cluster/nodes/test_disk_failures.py:166: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
ocs_ci/ocs/platform_nodes.py:216: in get_data_volumes
    pv.get().get('spec').get('vsphereVolume').get('volumePath') for pv in pvs
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7fc66ce352e8>

>       pv.get().get('spec').get('vsphereVolume').get('volumePath') for pv in pvs
    ]
E   AttributeError: 'NoneType' object has no attribute 'get'

ocs_ci/ocs/platform_nodes.py:216: AttributeError
```

**Comment by jilju** [comment] 2020-06-04 07:32
@ebenahar @rachael-george 
Is this a duplicate of https://github.com/red-hat-storage/ocs-ci/issues/1880 ?

**Comment by ebenahar** [comment] 2020-06-15 15:27
@jilju it's an enhancement for this test case. Closing https://github.com/red-hat-storage/ocs-ci/issues/1880

**Comment by ebenahar** [comment] 2020-06-15 15:27
@jilju yes, it is

**Comment by ebenahar** [comment] 2020-10-25 10:47
Currently, the test case is adjusted to dynamically provisioned clusters and not LSO. In addition to that, following the fix for https://bugzilla.redhat.com/show_bug.cgi?id=1787236, the handling of bad disks should be automatic over LSO.

**Comment by yitzhak12** [comment] 2021-05-03 08:41
This issue has been fixed by the PR https://github.com/red-hat-storage/ocs-ci/pull/3520

**Closed** 2021-05-03 08:42 UTC
