### ISSUE TITLE
When using the "bucket_factory_fixture" in tier3 tests it failed to delete the created buckets in the teardown part of the tests

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#7007] opened 2023-01-26 17:49 UTC
When using the "bucket_factory_fixture" in tier3 tests, in the teardown part of the tests, it failed to delete the created buckets. Here is an example of such a test: https://ocs4-jenkins-csb-odf-qe.apps.ocp-c1.prod.psi.redhat.com/job/qe-deploy-ocs-cluster-prod/6566/testReport/tests.manage.z_cluster.nodes.test_nodes_maintenance/TestNodesMaintenance/test_2_nodes_maintenance_same_type_master_/

As you can see it failed with the error:

>            raise TimeoutExpired(
>                     self.args, orig_timeout,
>                     output=b''.join(stdout_seq) if stdout_seq else None,
>                     stderr=b''.join(stderr_seq) if stderr_seq else None)
> E           subprocess.TimeoutExpired: Command '['oc', '-n', 'openshift-storage', 'delete', 'obc', 'oc-bucket-e1e97f68e6144d7ab185ff70e094fc']' timed out after 600 seconds

I am not sure if it's related to the tier3 tests, or if it's a general issue that needs to be fixed in the `bucket_factory_fixture` function.

**Comment by sagihirshfeld** [comment] 2023-02-01 12:40
I still haven't found the root cause for the error, but I'd like to share the following insights I've found so far:

- The NooBaa status logs revealed two AWS BackingStores in the rejected phase.
- One of these BackingStores was created along with bucket `oc-bucket-e1e97f68e6144d7ab185ff70e094fc`, which was created on top of it,  as part of `test_deletion_of_store_with_attached_buckets[AWS Backingstore]` that passed.
- This is the same bucket that failed to delete in the teardown of `test_2_nodes_maintenance_same_type[master]`
-  `test_deletion_of_store_with_attached_buckets[AWS Namespacestore]` also passed, but its Namespace Store and bucket seem to have been deleted successfully.
- `test_deletion_of_store_with_attached_buckets` is using the `bucket_factory_session` fixture instead of `bucket_factory`.

**Comment by sagihirshfeld** [comment] 2023-06-01 16:29
After taking a closer look at these cases, I noticed that the OBC's that their deletion timed out couldn't be found in the must-gather logs - as described in https://github.com/red-hat-storage/ocs-ci/issues/6552

Closing this one as a duplicate then

**Closed by sagihirshfeld** 2023-06-01 16:29 UTC
Labels: MCG, Squad/Brown, Squad/Red
