### ISSUE TITLE
local-storage-operator installation failed over OCP 4.5 and OCP 4.6  when used channel 4.5 | 4.6

### ISSUE THREAD

**Issue by prsurve** [red-hat-storage/ocs-ci#2324] opened 2020-06-17 18:26 UTC
creating temp yaml file with local-storage-operator data:
 [{'apiVersion': 'v1', 'kind': 'Namespace', 'metadata': {'name': 'local-storage'}, 'spec': {}}, {'apiVersion': 'operators.coreos.com/v1', 'kind': 'OperatorGroup', 'metadata': {'annotations': {'olm.providedAPIs': 'LocalVolume.v1.local.storage.openshift.io'}, 'name': 'local-storage', 'namespace': 'local-storage'}, 'spec': {'targetNamespaces': ['local-storage']}}, {'apiVersion': 'operators.coreos.com/v1alpha1', 'kind': 'Subscription', 'metadata': {'name': 'local-storage-operator', 'namespace': 'local-storage'}, 'spec': {'channel': '4.5', 'installPlanApproval': 'Automatic', 'name': 'local-storage-operator', 'source': 'redhat-operators', 'sourceNamespace': 'openshift-marketplace'}}]
23:27:54 - MainThread - ocs_ci.utility.templating - INFO - ['apiVersion\n--- kind\n--- metadata\n--- spec\n...\n', 'apiVersion\n--- kind\n--- metadata\n--- spec\n...\n', 'apiVersion\n--- kind\n--- metadata\n--- spec\n...\n']

LSO installation with channel 4.5 will fail as 4.5 is not yet GA so 4.5 channel is not yet opened 
as a WA we need to use n-1 as channel for LSO deployment

`Current Opened Channel`
![Screenshot (56)](https://user-images.githubusercontent.com/32088367/84935139-ed201400-b0f5-11ea-8f9f-9a003158de7e.png)

https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/deployment/deployment.py#L675-L677

**Comment by prsurve** [comment] 2020-06-17 18:26
@petr-balogh @clacroix12 fyi

**Comment by clacroix12** [comment] 2020-06-17 20:10
This will be addressed in my changes for #2242

**Comment by clacroix12** [comment] 2020-06-29 20:24
A workaround exists for this [here](https://github.com/red-hat-storage/ocs-ci/blob/master/ocs_ci/utility/localstorage.py#L172-L174). When the 4.5 channel exists for the LSO we should remove this workaround.

**Comment by ebenahar** [comment] 2020-07-07 18:16
Hi @clacroix12 @prsurve don't we need a BZ for this issue?

**Comment by clacroix12** [comment] 2020-07-07 21:53
@ebenahar I don't think this needs a BZ. The issue is we're trying to install the LSO using the channel that corresponds to the OCP version we're installing when that channel doesn't exist yet. 

I think the real solution to this is a more dynamic approach to deciding which channel we are using. If there is a way for us to programmatically determine which channels exist for the LSO before installation we should use that instead of our workarounds for the "latest" one not existing yet.

**Comment by ebenahar** [comment] 2020-07-08 07:15
Now understood, thanks!

**Closed** 2020-07-14 18:33 UTC
Labels: team/ecosystem, workaround
