### ISSUE TITLE
external ocs cluster deployment failed with parsing secret

### ISSUE THREAD

**Issue by vavuthu** [red-hat-storage/ocs-ci#3655] opened 2021-01-11 07:03 UTC
https://ocs4-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/qe-deploy-ocs-cluster/16153/consoleFull

```
 ocs_ci.ocs.exceptions.CommandFailed: Error during execution of command: oc create -f /tmp/external_cluster_secreth0gcjjz2.
E           Error is Error from server (BadRequest): error when creating "/tmp/external_cluster_secreth0gcjjz2": Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 76, error found in #10 byte of
```

**Comment by dahorak** [comment] 2021-01-13 08:14
This seems to be caused by wrongly formatted ``external-rhcs-lab1.yaml`` file. The base64 encoded value in `external_cluster_details` have to be whole on one line, not wrapped to 76 characters (which is the default value for `base64` command, you have to use `-w 0` parameter to disable wrapping).

I've reformatted the file and re-uploaded it to Jenkins Credentials, so I think we can close this issue.

**Closed by dahorak** 2021-01-13 08:14 UTC
Labels: bug
