### ISSUE TITLE
test_scale_million_cephfs_files: TimeoutExpired after 600 seconds

### ISSUE THREAD

**Issue by tiffanyn108** [red-hat-storage/ocs-ci#4589] opened 2021-07-21 01:57 UTC
Scale test cases are failing on 4.8 (OCS4-8-Downstream-OCP4-8-AWS-IPI-3AZ-RHCOS-3M-3W-scale-jenkins):
 * test_scale_million_cephfs_files[mgr] 
 * test_scale_million_cephfs_files[mon]
 * test_scale_million_cephfs_files[osd]
 * test_scale_million_cephfs_files[mds]

Error is seen in the logs:

```
 request = &lt;SubRequest 'million_file_cephfs' for &lt;Function test_scale_million_cephfs_files[mgr]&gt;&gt;

    @pytest.fixture(scope="class")
    def million_file_cephfs(request):
&gt; million_file_cephfs = MillionFilesOnCephfs()

tests/e2e/scale/test_cephfs_many_files.py:116:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/e2e/scale/test_cephfs_many_files.py:105: in __init__
    self.test_file_list = add_million_files(self.pod_name, self.ocp_obj)
tests/e2e/scale/test_cephfs_many_files.py:51: in add_million_files
    run_cmd(f"tar cfz {tarfile} -C {new_dir} .")
ocs_ci/utility/utils.py:456: in run_cmd
    completed_process = exec_cmd(cmd, secrets, timeout, ignore_error, **kwargs)
ocs_ci/utility/utils.py:489: in exec_cmd
    completed_process = subprocess.run(
/usr/lib64/python3.8/subprocess.py:491: in run
    stdout, stderr = process.communicate(input, timeout=timeout)
/usr/lib64/python3.8/subprocess.py:1024: in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
/usr/lib64/python3.8/subprocess.py:1867: in _communicate
    self._check_timeout(endtime, orig_timeout, stdout, stderr)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = &lt;subprocess.Popen object at 0x7f43d1fa3280&gt;, endtime = 11919.930568731
orig_timeout = 600, stdout_seq = [], stderr_seq = []
skip_check_and_raise = False

    def _check_timeout(self, endtime, orig_timeout, stdout_seq, stderr_seq,
                       skip_check_and_raise=False):
        """Convenience for checking if a timeout has expired."""
        if endtime is None:
            return
        if skip_check_and_raise or _time() &gt; endtime:
&gt; raise TimeoutExpired(
                    self.args, orig_timeout,
                    output=b''.join(stdout_seq) if stdout_seq else None,
                    stderr=b''.join(stderr_seq) if stderr_seq else None)
E subprocess.TimeoutExpired: Command '['tar', 'cfz', '/tmp/tmpe4scnilk/cephfs.tar.gz', '-C', '/tmp/tmpm0tgn3ih', '.']' timed out after 600 seconds

/usr/lib64/python3.8/subprocess.py:1068: TimeoutExpired
```

**Comment by wusui** [comment] 2021-07-21 23:32
I experienced this timeout when I tried to increase load to two million files.  I don't encounter it when I run this test alone on my own cluster with a million files, so I suspect that this may be a little slower when run in the regression suite after a lot of other activity.  I think that increasing the timeout value is  the right change here, and I will try it out with my own regression run.

**Comment by ramkiperiy** [comment] 2021-08-25 08:11
Closing this issue, since fix is already merged.

**Closed by ramkiperiy** 2021-08-25 08:11 UTC
Labels: scale, Squad/Orange
