### ISSUE TITLE
Adding a new node with vSphere causes terraform.tfvars file to have extra argument

### ISSUE THREAD

**Issue by yitzhak12** [red-hat-storage/ocs-ci#3934] opened 2021-03-03 11:42 UTC
When adding a new node with vSphere, the file `terraform.tfvars` have an extra argument at line 1 `compute_count = "6"`, which caused an error when trying to add another node:

> E           Error is 
E           Error: Missing newline after argument
E           
E             on terraform.tfvars line 1:
E              1: compute_count = "6"cluster_id = "ikave2-lso47"
E           
E           An argument definition must end with a newline.

This argument `compute_count = "6"` should be removed.

**Comment by yitzhak12** [comment] 2021-03-03 11:46
Here is the Jenkins job when I had this failure https://ocs4-jenkins-csb-ocsqe.apps.ocp4.prod.psi.redhat.com/job/qe-deploy-ocs-cluster/972/, but it occurred to me also a few times before.

**Comment by petr-balogh** [comment] 2021-03-03 12:49
This is duplicate of this one issue:
https://github.com/red-hat-storage/ocs-ci/issues/3894

**Closed by petr-balogh** 2021-03-03 12:49 UTC
